### ISSUE TITLE
auto-connect in GUI and CLI

### ISSUE THREAD

**Issue by pmkap** [mullvad/mullvadvpn-app#1002]
One can assume that the CLI auto-connect is for the daemon and completely independent from the GUI. However, it is not clear if the GUI auto-connect option is for the GUI or for the daemon or both. 

Playing around with the two options on my System (2019.6 Linux), I find that the two options are indeed distinctive. But they are not independent. I'm not sure whether this is intended, but let me explain my observations.

When the CLI auto-connect is changed, it never affects the GUI auto-connect. This is fine of course.

But when switching it off in the GUI, it ALSO switches of the CLI setting (according to `mullvad auto-connect get`). I think this can be problematic if a user is aware of the difference between GUI and daemon, only wants to disable the GUI auto-connect and ist then unprotected at reboot.

Furthermore, when switching auto-connect back on in the GUI, it leaves the CLI setting at off. It is a bit inconsistent that this is only in one direction affecting the daemon and could also lead to potential risks.

I think it would be good to have the two settings completely independent and maybe make an additional preference entry in the GUI for the daemon auto-connet. It could be called "auto-conect at system start".

One could also argue that the auto-connect setting in the daemon is too important to let the user disable it. E.g. in the case when the daemon process crashes (I know it's unlikely, but still possible) and gets restarted by systemd leaving the user unprotected. On the other hand this would it make impossible not to automatically connect at boot.

Sorry that this got so long, but I wanted to share all my thoughts on auto-connect.

**Comment by faern** [comment]
In the GUI, if you enable both auto-connect and launch on start, then it will enable auto-connect in the daemon. The daemon has an `auto-connect` setting and the CLI directly controls this setting. This daemon setting toggles whether or not starting the daemon (computer boot) should trigger a connect or not.

If you enable auto-connect in the *GUI* but not launch on start, then we don't want the daemon to connect on boot, because that is what we had before and it confused almost everyone. From the *GUI* perspective auto-connect means "connect when the GUI starts". And if you have the GUI on auto-connect and you *also* have the GUI to start on boot, only then we want the daemon to secure the computer as early as possible.

We have changed these settings many times back and fourth and come up with new names and tooltips for it. We think this is the best combination. Most users never use the CLI so the current GUI naming makes sense to a GUI-only setup. For power users of the CLI they sometimes get a slightly more confusing UX, and we should improve on the CLI help messages, but I don't think we should change how these settings interact with each other.

**Comment by pmkap** [comment]
I see. Thanks for the detailed explanation. This makes sense. So I close this issue.
