### ISSUE TITLE
Mullvad installer blocked by Avast.

### ISSUE THREAD

**Issue by therealearthe** [mullvad/mullvadvpn-app#1034]
Just tried to update to 2019.7 and the installer gets blocked by Avast. Now, I know that some AVs can detect a fake positive, but Avast?

**Comment by faern** [comment]
AV vendors have to find and whitelist software. So it's very common that AV software is suspicious about our releases the first few days. I would recommend disabling Avast while installing our app. If you don't want to do that I guess you will have to wait a while until they catch up with the latest release :man_shrugging: 

As a sidenote. This type of question is better directed to support@mullvad.net than at the issue tracker. Since this is not an issue with our software per se.
