### ISSUE TITLE
[Feature Request] Add an option for bookmarking/favouriting servers

### ISSUE THREAD

**Issue by FearlessHyena** [mullvad/mullvadvpn-app#1226]
It would be great if we could bookmark certain commonly used servers and if they were available either in a separate section of the app or at the top of the server list
Another place to add them would be in the context menu of the app notification icon in the tray. Right-clicking the icon would bring up the option to switch quickly to a different server from a list of bookmarked servers

**Comment by redactedscribe** [comment]
I'd like to see this too so that it would be possible to bookmark either countries, cities, or even individual servers. Quick access to a favorites list seems like it should be necessary, so I agree with the server list and tray icon ideas mentioned above. A lot of VPN providers have this basic feature built into their apps, and it's only after switching to Mullvad did I realize how convenient such a personally curated server list actually is.

**Comment by jacksongoode** [comment]
I would even add that a purely local implementation without attempting to associate it by key would be fine.

**Comment by Dex321x** [comment]
Would like this too. It's a bit annoying to cycle to all the servers to pick the one I like. A favorite feature would be very nice.

**Comment by olmoh** [comment]
Support for custom lists was added in [2023.6](https://github.com/mullvad/mullvadvpn-app/blob/main/CHANGELOG.md#20236---2023-12-06). Will close this issue, please open a new one if there are other requests for functionality related to this.
