### ISSUE TITLE
Unnecessary menu in systray on KDE 

### ISSUE THREAD

**Issue by tobias-kuendig** [mullvad/mullvadvpn-app#1276]
On KDE, the mullvad system tray icon does not open the app window on click but shows a menu with only one item:

![mullvad](https://user-images.githubusercontent.com/8600029/69782365-16587180-11b1-11ea-88d7-ce59414711a1.gif)

It would be great if this was skipped and the app window opens with a single click.

**Comment by faern** [comment]
It's not just under KDE. It's under a lot of desktop environments. It's a bit out of our hands since we simply use the Electron tray icon functionality and that's how this one works on modern desktop Linux. Modern desktop Linux in general moves away from tray icons. Many DE environments even come without tray icon areas sadly.

That being said, we will look into trying to make this better as soon as we have time. It's in the backlog.

**Comment by kayg04** [comment]
Thanks for all the work you're putting in.

About modern desktop Linux moving away from tray icons, I think it's only GNOME doing that? However a lot of us still use tray icons and like them where they're at. So instead of removing the "Mullvad VPN" item that shows up on right-click, would it be possible to add a few things like:

- Open app
- Reconnect
- Change server -> {expands to a dropdown of most recently connected servers}
- Disconnect 

while still being able to open the app with a single click?

**Comment by faern** [comment]
This was implemented in #2086. Going to close this as it's fixed.
