### ISSUE TITLE
[Feature Request] Allow access to more than 1 local network.

### ISSUE THREAD

**Issue by drossbox** [mullvad/mullvadvpn-app#1408]
It would be advantageous if the 'local network sharing' preference allowed specifying different local networks to be excluded from the tunnel, much as the wireguard android app implements. For example, the machine with Mullvad installed (Linux) resides on my 192.168.2.0/24 network, but I am unable to administer VM's residing on my 192.168.3.0/24 network whilst also maintaining a VPN connection, as an attempt to SSH will result in 'no route to host'.

**Comment by faern** [comment]
You can fix this by properly adding a route to your other local network. The "local network sharing" setting unlocks all private/unroutable IP ranges in the firewall already. The problem is that you don't have any route for your `192.168.3.0/24` network. As such it will be sent to the default route, which I guess is your router. Your router will then properly send it to your other LAN. But when Mullvad is active it is your default route, so it will collect this traffic. If you just add a routing table entry saying that `192.168.3.0/24` should go out via your physical network adapter this will be solved.

**Comment by drossbox** [comment]
> You can fix this by properly adding a route to your other local network. The "local network sharing" setting unlocks all private/unroutable IP ranges in the firewall already. The problem is that you don't have any route for your `192.168.3.0/24` network. As such it will be sent to the default route, which I guess is your router. Your router will then properly send it to your other LAN. But when Mullvad is active it is your default route, so it will collect this traffic. If you just add a routing table entry saying that `192.168.3.0/24` should go out via your physical network adapter this will be solved.

You're absolutely correct, this solved my issue immediately. Many thanks.
