### ISSUE TITLE
Allow disable of leak protection while connecting

### ISSUE THREAD

**Issue by shamilovtim** [mullvad/mullvadvpn-app#1473]
The leak protection while connecting (empty outline lock in toolbar) when it's enabled with autoconnect basically breaks almost all public wifi hotspots and in general is a huge nuisance. Please allow us to disable this feature.

**Comment by faern** [comment]
You mean because it blocks the captive portal / wifi login page? Yes, this is a known issue, but doing anything about it would also be a huge security risk.

Allowing traffic to flow unencrypted would essentially disable the "kill switch". As such, if you are happily connected and for some reason the tunnel breaks, so the app reconnects, then you would be leaking for a while, possibly without even knowing. This is why the app requires the user to explicitly disengage the VPN before it will allow any traffic to leave the computer unencrypted.

**Comment by shamilovtim** [comment]
@faern Thanks for answering. I'm not using the killswitch right now. However while the app tries to make a connection it gives me this icon: 
<img width="23" alt="Screen Shot 2020-02-10 at 2 56 05 PM" src="https://user-images.githubusercontent.com/3495974/74184844-82297280-4c15-11ea-8cb8-c422239839d5.png">. It's giving me an automatic killswitch only during connection. However, what's the point of that when I don't have a killswitch on BEFORE my connection? I've already leaked. As it stands the more fully featured killswitch / firewall which lets me turn it off is unusable because it breaks almost all wifi including my home wifi. However, this one which has no setting to be turned off is completely unnecessary for me, because without the fully featured killswitch on, I know I've already leaked from before my connection.

There needs to be a setting for this feature, it's quite annoying because right around the time I am enabling mullvad is around the time I happen to be connecting to a network. Without a killswitch / firewall on to begin with I don't need leak protection. I know I am already leaking because I have connected to the internet without any kind of firewall or killswitch on in the first place.

**Comment by shamilovtim** [comment]
Solution: allow fine grained control to killswitch during initial connect, killswitch during disconnect, or killswitch during both. Many people will not need the initial connect killswitch because the firewall does not play nice with most of our wifi.

**Comment by faern** [comment]
I think there is a mixup of terminology here. And/or I don't understand the use case or scenario.

> I'm not using the killswitch right now

If you are using this app, you are using the "kill switch". Because we have no setting for it. There is no way to disable it. It's always on. And I write it in quotes because we usually don't like to call it that. You can read more about it in detail in our app security document. Most importantly is probably the section on the "kill switch": https://github.com/mullvad/mullvadvpn-app/blob/master/docs/security.md#kill-switch

> ... it breaks almost all wifi including my home wifi.

> Many people will not need the initial connect killswitch because the firewall does not play nice with most of our wifi.

So this issue is *not* specifically about captive portals that you need to visit to log in to a wifi? Well then we have a bug. The app should allow the computer to connect to WiFis while the app security is engaged. From the icon screenshot I'm guessing you are on macOS, correct? Yes, we are aware there are cases where some users fail to connect to wifi while the app is engaged. We have not yet had the resources to investigate that bug, but given that you also report it as an issue we know it still happens, so we might prioritize it higher.

> However, this one which has no setting to be turned off is completely unnecessary for me, because without the fully featured killswitch on, I know I've already leaked from before my connection.

The icon you post the screenshot of is when the app blocks all network traffic and tries to connect, but it has not yet established a working tunnel (i.e. connecting state). You are not leaking during this state. And that's the point, people get to that state by clicking on the "Secure my connection" button. From the moment they push that button we guarantee no traffic leaves your computer unencrypted until you explicitly push the "Disconnect"/"Cancel" button. *Before* you push the "Secure my connection" button you will of course be leaking, but that is by your own choice, since you have not yet engaged the VPN.

> ... right around the time I am enabling mullvad is around the time I happen to be connecting to a network. Without a killswitch / firewall on to begin with I don't need leak protection.

Why do you enable Mullvad if you don't need leak protection? If it plays badly with your wifi, why don't you enable it after you have connected to the wifi?

> Without a killswitch / firewall on to begin with I don't need leak protection.

You do have a kill switch / firewall if you use the app. See above link to security document.

**Comment by shamilovtim** [comment]
> Why do you enable Mullvad if you don't need leak protection? If it plays badly with your wifi, why don't you enable it after you have connected to the wifi?

It just happens frequently. I'd be far more covered by Mullvad if you just let me turn off the built in killswitch that you don't have a setting for. The issue is that I constantly have to turn off mullvad and then I forget to re-enable it. Since you don't provide the flexibility to disable the killswitch, it's quite often where I just have it off and I've forgotten to use it.

**Comment by pouriamoosavi** [comment]
How is this mark as complete? I still can't find a way ti disable kill switch.
