### ISSUE TITLE
Android app cannot see the server list in China

### ISSUE THREAD

**Issue by stevenfang1997** [mullvad/mullvadvpn-app#1526]
My friend in China can't connect to the Android app because the server list is even not shown. I know China is actively blocking internet access of VPNs, but I think there should be a workaround to this? I mean to make the server list visible at least.

![signal-2019-10-28-010535_1](https://user-images.githubusercontent.com/37974764/75034190-674ddc80-54f8-11ea-91fe-d980b4512035.jpg)

**Comment by faern** [comment]
Bundling the server list inside the app, so it's available on first start even if our API is blocked was recently merged in #1486. So the next release for Android will include the server list. Then your friend should be able to see the servers.

Whether or not they will be able to connect to them remains to be seen, but that is somewhat unrelated.

I'm closing this issue since the server list part has been fixed on master. Please re-open if it's still a problem after the next release.
