### ISSUE TITLE
iOS Split Tunneling

### ISSUE THREAD

**Issue by cwmke** [mullvad/mullvadvpn-app#1583]
I see iOS looks like it's being worked on now. I am wondering if it's being designed with split tunneling in mind as I use AdGuard in combination with ProtonVPN currently. This sets Proton up as a personal VPN allowing for DNS to run through AdGuard (allows some ad blocking.)

I was testing out Mullvad with the Wireguard and OpenVPN apps but they don't seem to support split tunneling at all. It's a funny situation since Mullvad's desktop applications are fantastic while Proton's mobile apps are fantastic. Below is AdGuard's preference screen for setting up a split tunnel.

![AdGuardTunnelMode](https://user-images.githubusercontent.com/1923967/77106600-5c01aa00-69ed-11ea-88b8-7a2feaca3958.png)

**Comment by faern** [comment]
No, the Mullvad VPN app for iOS will not be a "Personal VPN". This is because a "Personal VPN" can only run one of the natively supported protocols (IPSec and a few more). Mullvad does not use these older protocols. Our iOS app will use WireGuard only, and as such it must not be a "Personal VPN".

You can see this answer for some more details: https://apple.stackexchange.com/a/376694

However, over time (not in the first iteration) we will support what we usually refer to as "split tunneling". Meaning you can allow certain apps to go outside the tunnel if you want to. But that's a different feature than the one you are describing.

**Comment by cwmke** [comment]
Thanks for the link; that makes a lot of sense why it won't be supported. Will there be anyway to use a custom DNS provider? That's essentially what this boils down to for me as this is the only way to block trackers device-wide on iOS that I have found.

**Comment by faern** [comment]
The first version of the app will not support setting a custom DNS, no. The first version will be just the essentials. It might be added at a later point.
