### ISSUE TITLE
[ios] Support for ios 12

### ISSUE THREAD

**Issue by Strykeros** [mullvad/mullvadvpn-app#1748]
#795  Issue report

Operating system: 

ios 12.4

App version: 

latest

### Issue description

It would be very nice, if mullvad would also support ios 12. I have an iphone 6, that does not support ios 13.

**Comment by faern** [comment]
Sorry. But to be able to iterate faster and get the app out we decided to go with the latest APIs and support only the newest versions. iOS 13 is already used by >70% of iOS devices and constantly growing. We know we left iPhone 6 users unsupported sadly :(

Supporting older devices now would be a large effort, since it would involve replacing all components that use iOS-only APIs. It's just not worth it for an already small target group that is by definition also shrinking constantly.

**Comment by faern** [comment]
We went ahead and fixed iOS 12 support anyway. And it just went live! The latest version on App Store now supports iOS 12 and newer. https://mullvad.net/en/blog/2020/9/11/mullvad-vpn-also-available-ios-12/
