### ISSUE TITLE
After removal, unable to have DNS dynamically set to anything else other than Mullvad default (10.64.0.1)

### ISSUE THREAD

**Issue by jorp** [mullvad/mullvadvpn-app#1885]
## Issue report

Operating system: Fedora 32

App version: 2020.5 

### Issue description

After quitting and killing all mullvad processes, disabling any daemons, and removing all mullvad-related files, NetworkManager is unable to set default DNS that should be obtained by DHCP. It seems that NetworkManager is still somehow getting 10.64.0.1. I've grepped my entire system for this IP and was unable to find some stray config file that could possibly be setting this IP still. I am not using systemd-resolved.

**Comment by pinkisemils** [comment]
I'll have a look at this behavior. I'd wager that the daemon crashed and did not restore NetworkManager config properly. The uninstallation script should stop the daemon gracefully, which should in turn remove the DNS configuration. We use 4 different ways to manage DNS, because there are too many distros that each do things differently. In this case, we set a global DNS configuration in NetworkManager, which unfortunately is a configuration option that is not exposed in any of NM's frontends.

**Comment by kubrickfr** [comment]
Hello.

I had the same issue and I have been investigating for a few days. It looks like mullvad is not always cleaning up after itself.
https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/484#note_556920

Solution is here (backup that file first maybe?)
https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/484#note_556816

**Comment by jorp** [comment]
> Hello.
> 
> I had the same issue and I have been investigating for a few days. It looks like mullvad is not always cleaning up after itself.
> https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/484#note_556920
> 
> Solution is here (backup that file first maybe?)
> https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/484#note_556816

Yup, `/var/lib/NetworkManager/NetowrkManager-intern.conf` did end up being the culprit. Not sure if this issue should be closed, or if the contributors/maintainers want to keep this open as an action item.

**Comment by pinkisemils** [comment]
Since #1965 is merged now, this should no longer be an issue. We haven't released a stable version with these changes just yet, but 2020.6 should have these changes. I'll close the issue for now.
