### ISSUE TITLE
[Feature Request] retrieve the private key of the wireguard public key used in the app

### ISSUE THREAD

**Issue by NewRedsquare** [mullvad/mullvadvpn-app#2060]
I'm actually using mullvad on 5 devices but on android, due to the lack of multihop in the app, i also use the wireguard app. It means, that i need now 6 keys ( but the maximum is 5 ).

It can be useful to retrieve the private key used in the Mullvad app so i can use it with wireguard app on the same device.
Is it not implemented due to some "security problems" this functionality can create ?

**Comment by faern** [comment]
Yes, due to security we don't want to expose it. The key system is not at all designed for re-using the same key in multiple apps.

We will eventually have multi hop on mobile as well. But until that happens you will likely have to survive with only the standard WireGuard app or get another Mullvad account for five additional keys.
