### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by BigJCM** [mullvad/mullvadvpn-app#2131]
## Issue report

Debian 10

2020.5_amd64

### Issue description

When installing on Debian 10 I get the error "Failed to enable unit: Unit file /opt/Mullvad VPN/resources/mullvad-daemon.service does not exist." The error is similar to issue #1081

**Comment by faern** [comment]
Maybe you can upgrade systemd and other packages in your system? We still believe this is caused by some package not correctly handling spaces in paths. It works for us on our up to date Debian 10 machines. We have not seen this in a long time now. Or if you have everything fully up to date, then it might be a new problem?

**Comment by BigJCM** [comment]
I was able to fix this by installing on another debian 10 system and copying the .service file onto this machine. I believe the problem was caused by having old files from a previous version of the app still on the system. Apologies for creating the issue.
