### ISSUE TITLE
Unable to use mullvad-cli

### ISSUE THREAD

**Issue by AntonNarkevich** [mullvad/mullvadvpn-app#219]
I'm using mullvad on Mac. I really wanted to make use of a `cli` interface.
I moved to `/Applications/MullvadVPN.app/Contents/Resources` and tried running:
`./mullvad status`.

Unfortunately it gives me an error:
```
Error: Unable to call backend over RPC
Caused by: Unable to call RPC method get_state
Caused by: Invalid reply, no 'result' field
```

Would appreciate any help.

**Comment by faern** [comment]
For the `2018.1` release the CLI does sadly not work. This is because of the unfortunate combination that the daemon requires frontends to authenticate, for security reasons. The CLI in the `2018.1` release does not support this type of authentication. We should probably have not shipped the CLI binary with that release.

All of this has been fixed in the current `master` branch. So in the upcoming `2018.2` release the CLI can be used and will perform proper authentication. If you need to get going before the official release you can build your own version by checking out the code and following the readme. In general, if you have Rust and `yarn` set up you should be able to run `./build.sh`

**Comment by faern** [comment]
The CLI should work as expected on the latest beta that is now out: https://mullvad.net/en/guides/beta-app/

So I'm closing this issue. Please re-open it, or open a new one, if you have further issues with the CLI.
