### ISSUE TITLE
[Feature Request] Add "Always require VPN" to the main screen

### ISSUE THREAD

**Issue by emilmelnikov** [mullvad/mullvadvpn-app#2234]
## Issue report

Operating system: macOS 10.15.7

App version: 2020.6

### Issue description

In some cases it's necessary to temporary disable the "Always require VPN" feature, e.g. in order to connect to a work VPN, or some other service that blocks VPN servers. Moving it to the main screen would greatly help people who need to do this regularly.

Since not everybody needs this feature (I guess so because it is located in the "Advanced" settings section), maybe the switch on the main screen could be visible only if a user has already enabled this feature in the settings.

**Comment by faern** [comment]
So your use case is that you usually have "Always require VPN" on and then you toggle the VPN connectivity on and off in order to go between the states "Completely blocked internet" and "Tunnel everything via Mullvad". But sometimes you need to reach the state "No Mullvad VPN and also unblock the entire internet" in cases where you need to enable another VPN solution?

The problem is that someone else likely need to toggle some other setting on and off sometime, should we add their setting to the main screen also? The main screen will very easily become extremely cluttered. So I don't think we can move any setting there. But the request is noted.

You can set up some automation for this using our CLI if you wish. The command `mullvad always-require-vpn set off` will turn "Always require VPN" off, and `mullvad always-require-vpn set on` will turn it back on.

**Comment by emilmelnikov** [comment]
> The problem is that someone else likely need to toggle some other setting on and off sometime, should we add their setting to the main screen also? The main screen will very easily become extremely cluttered. So I don't think we can move any setting there. But the request is noted.

I understand the argument. However, may I suggest at least displaying the "Always require VPN" status on the main screen even when the VPN client is connected? It would be consistent with the disconnected state screen, and also would reassure people that this feature is enabled.

> You can set up some automation for this using our CLI if you wish. The command mullvad always-require-vpn set off will turn "Always require VPN" off, and mullvad always-require-vpn set on will turn it back on.

I've tried the CLI: it's great, and faster for me than clicking through menus, thanks!

**Comment by faern** [comment]
When the VPN is connected the "Always require VPN" option does nothing. It only alters the behaviour in the disconnected state.
