### ISSUE TITLE
Mullvad blocks VM internet connections even when disconnected from VPN

### ISSUE THREAD

**Issue by davidwinter** [mullvad/mullvadvpn-app#2320]
## Issue report

Operating system: `Ubuntu 20.10`

App version: `2020.7`

### Issue description

If I have Mullvad installed on Ubuntu, but disconnected from any server, it interferes with VM internet connectivity. I use multipass, and any containers that I have setup, are unable to connect to the internet, and I have to completely uninstall Mullvad and restart my machine before they can communicate with the internet.

Steps to reproduce.

1. Install Mullvad via `dpkg -i path/to/mullvad.deb`
2. Reboot. Mullvad should auto-launch at startup, but **do not** connect to the VPN.
3. Install multipass via `sudo snap install multipass`
4. Create a new VM `multipass launch --name test-mullvad`
5. Connect to VM via `multipass shell test-mullvad`
6. Try and ping Google with `ping 8.8.8.8`

**Just to reiterate, this is when not connected to Mullvad, but the client is installed.**

To resolve, either:

- Uninstall Mullvad and reboot your computer
- Within Mullvad preferences, enable Local network sharing, and then reboot your computer

The latter option I don't think is a true resolution, as when not connected to Mullvad VPN, it should not be blocking local network traffic.

**Comment by pinkisemils** [comment]
I'll take a wild guess and assume this is related to how our app was trying to do split tunelling in 2020.7. We have made significant changes, but we're in an upcoming release, but we haven't tested for this specific tool. I can report that using docker, podman and libvirt/qemu seems to work just fine, so maybe there is some config option in multipass that can alleviate the connectivity issues?   We'll try and investigate what multipass does differently and see if that can be accommodated.

**Comment by pinkisemils** [comment]
On both 20.04 and 20.10, I failed to reproduce the issue. I did a reboot after installing multipass before connecting because I failed to enable virtualization extensions for the guests. Regardless, it's a known issue that containers and VMs will probably not have working networking without allowing LAN traffic, but it should always work when disconnected, unless the user has specifically enabled _Always require VPN_, which will block all traffic unless connected to a tunnel.
