### ISSUE TITLE
[Feature Request Android]: Ability to Choose Which Default UDP Port Wireguard uses.

### ISSUE THREAD

**Issue by Jpersh27** [mullvad/mullvadvpn-app#2424]
- Allow users the ability to chose which default UDP Port Wireguard uses to establish a connection for the VPN tunnel.
(By default Wireguard uses UDP Port 51820)

-- I have encountered some connection issues on public WiFi networks in the USA when using Mullvad. My connection is blocked, and I'm unable to connect to the internet altogether while connected to the VPN tunnel. However, once I disconnect from the Mullvad VPN tunnel I am able to resume using the internet once again.
 (I don't want to go unprotected when using public WiFi. I want to be able to be secure and safe on open and unprotected public WiFi networks)

--- Some suggestions on UDP ports Wireguard could use: UDP 53, UDP 1194, UDP 2049, UDP 2050, UDP 30587, UDP 41893, UDP 48574, and UDP 58237. 

---- A good place to put this feature could be under the “Settings" tab under “Advanced".

I hope this feature is considered because it is badly needed. It would especially help users who have trouble circumnavigating public WiFi networks, and Network Firewalls set up in countries where connections from VPNs are often blocked/restricted by (ISPs) or Governments.

**Comment by faern** [comment]
You can already choose port 53 if you want under advanced. If "Automatic" is selected the app uses a random port, and not 51820.

You can also specifically set a custom port with our CLI. If you start your terminal/console and run the command:
```
mullvad relay set tunnel wireguard <port>
```
With `<port>` replaced for your desired port, then it will use that. A limitation however is that it will only work with ports in these ranges: 4000-33433, 33565-51820 and 52000-60000. So most of the higher ports you suggest can already be used if you want to. It's just a bit hidden and tricky to configure since it requires the command line tool. I hope you get it to work. We will consider adding more ports to the graphical interface! Thank you for the suggestion.

**Comment by Jpersh27** [comment]
@faern Thank you for the response and for the explanation!

1.) Now is there any plans to add this feature on the Mobile Apps of Mullvad?
(Specifically the Android version of Mullvad)

- Sorry I wasn't more specific. I currently only use Mullvad on my Android devices and not on the desktop Windows application of Mullvad. 

-- I run into connection issues specifically on open public WiFi networks when using the Mullvad Android App. I don't have any issues with the application on my home internet however.

Thanks again and looking forward to your reply.
