### ISSUE TITLE
[Android Request]- Monthly Builds, Updates, and Improvements.

### ISSUE THREAD

**Issue by Jpersh27** [mullvad/mullvadvpn-app#2507]
@axti @faern

• The Android app for Mullvad hasn't received a new release in almost 5 months now (last release was in November 2020)

• No updates are ever provided on your website blog about future plans or updates  regarding your Mobile Applications. 

• The Windows application for Mullvad has received at least if not more than 10 or 15 Beta builds/Stable releases compared to 0 new releases in any form for the Android Mobile application of Mullvad. 

• The Android application of Mullvad is Basic and lacking many key features compared to Several other VPN providers.

1.) I would like to know if you ever plan on developing a roadmap and outlining what your plans are for the mobile versions of Mullvad in the year 2021? 

• Suggest creating a blog post on your website with a timeline listing various times  throughout the year and what will be released during that time frame. We are almost 3 months into the year already and no planned release or mentioning of a release.

2.) Any commitment or plan to release monthly or even weekly updates to the Android application?

• It would be nice to see better support regarding your Mobile Applications and more transparency and updates regarding when the updates will be released to the paying users of your service. I am one of those paying users and have been for over a year now and it's a shame I have to think about switching VPN Services because the Mobile Applications for the VPN service are lacking support and features. (Specifically the Android version)

**Comment by faern** [comment]
Could you be more specific on what features it is that you are missing? It's very likely those features have issue threads here on github already. Giving a thumbs up on those issues can be helpful so we know what features are most requested.

No we don't have a concrete roadmap with approximate release dates for certain features. And we never had on any platform. We always prefer correctness over speed. So we develop something until it's done, not until a certain date passes.

Yes. It was a long time since the last Android release. Since then we got one extra Android developer, so maybe it will pick up some speed shortly! Also, since then we started a pretty large refactoring of the app, splitting it into more processes, hopefully resulting in a more stable app in the end. But the large refactor made the next release take time.

We are currently working on:
* Finishing the refactoring mentioned above
* Making the split tunneling view a lot nicer
* Get rid of some memory leaks

When all of those are done we plan on releasing the next version. The next version will also contain a ton of other nice stuff. Such as custom DNS. We still don't know when this will happen. Because it's really really hard to estimate development time for the remaining features. And we also don't know how many issues we hit during internal testing before we can confidently release it to the public. Sometimes that's smooth sailing and we can release fast. Sometimes we find some flaw that needs time to be re-worked.

With regards to transparency. All the code and the pull requests are open source. So you can in detail follow what is happening to the app in real time. But no, the future plans are not really public. Mostly because priorities change constantly as new info becomes known. And having a roadmap that constantly changes makes no sense :)

**Comment by Jpersh27** [comment]
@faern- Thank you for the very detailed information regarding the service and the Android application. 

I do have some other questions below if you could answer them and provide further clarification for me please.

1.) Besides @axti who is the other Android developer for Mullvad? Or does the new developer not have a GitHub profile page?

• You mentioned above that “Since then we got one extra Android developer, so maybe it will pick up some speed shortly"

2.) Will the next release happen in the next few weeks? Or does it look to be longer than that? 

• You mentioned in a previous issue I started the following- https://github.com/mullvad/mullvadvpn-app/issues/2430

Features that are missing from the Android application- “Listed in order of importance"

1.) Adblocker- (DNS based or Host File based)- 

• “That Blocks Ads, Malware, and trackers”

2.) Choose Which Default UDP Port Wireguard uses to tunnel. 

• Common UDP ports such as- 53, 80, 443, and Wireguards default UDP # 51820 etc...

3.) Custom DNS Feature

• Ability to connect to Adblocking DNS Services such as AdGuard, NextDNS, etc...

4.) Mock location feature (For users using Android version 7 and above) 

• You have to enable developer settings on your Android device and select the application that utilizes the “Mock location" feature under the “Debugging" section. It will say “Select mock location app" Relatively easy to do and easy to create a step by step blog post stating how to enable this feature. No many steps...

**Comment by faern** [comment]
1. @jvff is the other Android developer. As you can probably see from commit history, he has written most of the Android PRs up until very recently.
2. I can't give any ETA. It will come out when it's ready. Expect at least two two more weeks.

**Comment by faern** [comment]
I'm going to close this issue as it does not track any single issue or feature in a meaningful way.
