### ISSUE TITLE
Tray icon duplicates in %TEMP%

### ISSUE THREAD

**Issue by aeruower** [mullvad/mullvadvpn-app#2636]
## Issue report

Operating system: Windows 10

App version: 2021.2

### Issue description

I've noticed the Mullvad app creates tens of tray icons over time in %TEMP%.
![temp dir](https://i.imgur.com/gZ6wxdl.png)
There is a repeating pattern of 10 icons.
![pattern](https://i.imgur.com/VUbRVZG.png)
One icon from two different groups of icons is the same icon.
![dupes](https://i.imgur.com/MaWbzYa.png)
sha256sums:
```
ebd3e87cd741aa70baa0b8556d6588c9efe96c11c788ca60c2b4d08cca2b5de7  5f2690c0-445e-41bf-816e-63c42c7cc0dc.tmp.ico
ebd3e87cd741aa70baa0b8556d6588c9efe96c11c788ca60c2b4d08cca2b5de7  408a5e79-51e0-40eb-aa60-2b4a6d78ae63.tmp.ico
```
Why not to reuse the same icons instead of duplicating them?

**Comment by faern** [comment]
Thank you for reporting this. It's clearly a bug. They should not have to be copied to temp at all in the best of worlds but just used from our resource directory.

**Comment by raksooo** [comment]
All the resources in the Electron app is bundled into an asar-archive. Electron is able to read files from this archive without extracting them but as I've understood it the Windows taskbar APIs are not, this means that the icons have to be extracted before being used for the tray icon.

The reason for the duplicate set of icons is probably due to a reinstall or restart of the app, I'm not sure exactly when the duplicates appear.

[I've previously reported that icons aren't cleaned up when not in use anymore, on the Electron repo](https://github.com/electron/electron/issues/22500), and it was closed with this explanation:
> Because these files are created in Temp they can (and will) be cleaned by the OS whenever it wants to. Them being left behind is ok as the OS will clean this folder up.
