### ISSUE TITLE
Mullvad socket is accessible from all accounts

### ISSUE THREAD

**Issue by alxpettit** [mullvad/mullvadvpn-app#2639]
## Issue report

Operating system: Ubuntu 20.10

App version: 2021.2

### Issue description

Mullvad daemon control socket defaults to being globally accessible. This seems to me to be a serious security risk. It would be better to have the file owned by mullvad:mullvad or somesuch, and have the mode set to 660.

**Comment by faern** [comment]
This is by design. I'll quote https://github.com/mullvad/mullvadvpn-app/blob/master/docs/security.md#desktop-system-service

> Locally running malicious programs are outside of the app's threat model.

So "serious security risk" depends on your threat model. If you have malicious software running locally or malicious users with accounts on your machine, we have concluded that you probably have much worse problems than someone fiddling with your VPN settings.

We could of course lock it down in some way (for example as you described by creating a dedicated group). But then an admin would have to specifically grant certain users access. This would be more complex for the average user who is typically on a single user machine anyway and would not benefit much. We could add it as a feature behind an environment variable and expose it to more advanced users for sure.

**Comment by alxpettit** [comment]
an environment variable feature would definitely solve this use case :)

**Comment by faern** [comment]
This has been fixed and released. If you run version `2021.4` or newer you can set the environment variable `MULLVAD_MANAGEMENT_SOCKET_GROUP` to control which unix group will own the socket. Only that group will have access to managing the daemon. See https://github.com/mullvad/mullvadvpn-app/blob/master/CHANGELOG.md#20214-beta1---2021-06-09
