### ISSUE TITLE
[Mullvad Ad + Tracker Blocker] Viber Ads

### ISSUE THREAD

**Issue by 8227846265** [mullvad/mullvadvpn-app#2816]
## Issue report

Operating system: Windows 10 x64

App version: 2021.3

## Issue description

Setup:

- Enabled Mullvad Ad + Tracker Blocking via Custom DNS = 100.64.0.3
- Viber installed and running

Viber Ads seems to be running even with Mullvad Ad + Tracker Blocker DNS is enabled.

Reference:

- There seems to be an alternative way to block ads on Viber via HOST method which works.
- https://www.joe0.com/2019/01/24/how-to-disable-viber-annoying-ads-on-windows-and-macintosh/
- Perhaps it can be implemented on future releases of Mullvad's ad & tracker blocking feature.

## Screenshot
![image](https://user-images.githubusercontent.com/66582769/123507004-baf6aa00-d699-11eb-994e-c9ac57992df4.png)

**Comment by faern** [comment]
Thank you for reporting this. I see we are blocking the `...viber.com` domains, but not the rakuten.com one. We'll update our blocklist!

The hosts file solution you link to is equal to our DNS based solution. In the end all it does is to prevent the lookup of domain names that host ads/trackers. Exactly which domains we block is not on the app, that's a feature of our infrastructure. You can see the list of domains we currently block over here: https://raw.githubusercontent.com/mullvad/dns-adblock/main/output/relay/relay_adblock.txt. Questions about what domains we block or requests to improve it should go to support@mullvad.net rather than this app specific issue tracker, thank you.

**Comment by 8227846265** [comment]
Noted. I'll send an email next time.
