### ISSUE TITLE
[Feature Request] Static network adapter IP on weekly re-key ?

### ISSUE THREAD

**Issue by ganego** [mullvad/mullvadvpn-app#2842]
## Issue report

Operating system: Debian stable

App version: 2021.3

### Issue description

I bind various programs directly to a network adapter because I do not want to tunnel everything. This works fine, except that every week on rekeying the connection, the adapter IP changes (`sudo ifconfig` -> "wg-mullvad" -> 10.xxx.xxx.xxx).

Is this something that I could change or does the VPN server give me this IP?

**Comment by faern** [comment]
The reason to introduce automatic key rotation in the first place was to rotate the user's IP. The key rotation itself is not important, it's that users get new IPs periodically. This is done to improve anonymity. If you somehow leak your tunnel's private IP that could potentially be traced back to you. But if users rotate keys regularly then this does not work well over time. With that as background, it would be backwards to introduce key rotation without IP renewal. The more correct solution for your use case would be to disable key rotation. This was possible in older apps, but was recently forbidden. We now make assumptions that app users rotate keys regularly.

Maybe you can try to bind your various programs to the *adapter* rather than the *IP*? Would that work?

**Comment by pinkisemils** [comment]
If you do not want to tunnel everything, you might be better off using `mullvad-exclude` to launch programs you want to exclude from the tunnel.

**Comment by pinkisemils** [comment]
After some further discussion, we think it'd be better if you were to elaborate on what it is you're trying to do.

By just binding a process to a specific interface, it shouldn't be able to communicate with the network at all (if you've not allowed LAN traffic) or just send LAN traffic (if you've allowed it). However, if all you want to do is send LAN traffic, you shouldn't have make sure a process is bound to a specific interface - as long as you have a route for the subnet you're trying to reach and you've enabled LAN traffic, everything should just work.

However, if you're trying to make sure that a process is not sending it's internet traffic through the VPN tunnel, then you should use `mullvad-exclude`, or check out the split tunneling features of our CLI. 

In the case that you can successfully send internet traffic from arbitrary applications by just making sure they are bound to a specific interface, please send a problem report and elaborate on your setup - in this case there's a very serious bug and we should be looking to fix that ASAP.

**Comment by ganego** [comment]
> Maybe you can try to bind your various programs to the _adapter_ rather than the _IP_? Would that work?

What you wrote makes sense, I did not know the background. Thank you, I will look into it. 

@pinkisemils The program allows me to bind it to a specific IP. I bound the program to the local mullvad wireguard adapter 10.x.x.x IP - I want to send all traffic for this program via VPN (and still access it from within my LAN too). 
I now tried to bind it to the mullvad wg adapter name and this seems to work too.  
I do allow LAN traffic in the mullvad app.

**Comment by pinkisemils** [comment]
Ah, so you're wanting to make sure that a specific application is routed through our tunnel, rather than to make sure an application is not routed throuh our tunnel? Well, in this case, if you're using our application and you are not changing the firewall rules that our application applies, all applications that are not spawned via `mullvad-excude` or have their PID's excluded via `mullvad split-tunnel` will be routed through the tunnel. 

That's kind of the main selling point of our client - as soon as you click the button to connect (or as soon as the daemon starts to connect), all traffic should flow through the tunnel unless it's routed to a LAN.

So, when you say you don't want to tunnel everything, I want to make sure we are in agreement about what is getting tunelled and what is not. All traffic should be flowing through the tunnel when you're connected, and binding a socket to a specific interface should not change that.

**Comment by ganego** [comment]
> Ah, so you're wanting to make sure that a specific application is routed through our tunnel, rather than to make sure an application is not routed throuh our tunnel?

Correct. And thankfully the application offers to bind itself to some IPs/adapter, so it's quite easy. 

I'll close the issue, since using the adapter name seems to work. Thank you for your replies and sorry if I caused some confusion.
