### ISSUE TITLE
Start in Main Menu

### ISSUE THREAD

**Issue by anon97945** [mullvad/mullvadvpn-app#2878]
## Issue report

Operating system: Windows 10 64bit

App version: 2021.4

### Issue description

It would be nice to close the tray menu and start the app in the main menu every time. Currently it always starts where you were last, e.g. the settings menu...

**Comment by faern** [comment]
With "main menu" do you mean the app's main view with the map, your connection state and the connect/disconnect button?

It's currently by design so that you can leave the app and come back to the same place. If for example you just leave temporarily to double check something in another program and then come back. But I agree that it might be strange to come back where you left off if some time has passed. We can consider having a timeout where if you have not opened the app in X minutes it will open in the main view again.

**Comment by anon97945** [comment]
Yes, this would be great and yeah, this is exactly what i mean.
