### ISSUE TITLE
DNS doesn't work if DoT is enabled in systemd-resolved

### ISSUE THREAD

**Issue by ikorolev93** [mullvad/mullvadvpn-app#2893]
## Issue report

Operating system: Fedora 34 (Workstation Edition)

App version: 2021.4

### Issue description

If DNS over TLS is enabled in systemd-resolved:

```
$ grep DNSOverTLS /etc/systemd/resolved.conf 
DNSOverTLS=yes
```

then after connecting, domains will not resolve. Looking at the output of resolvectl:

```
$ resolvectl
Global
           Protocols: LLMNR=resolve -mDNS +DNSOverTLS DNSSEC=yes/supported
    resolv.conf mode: stub
Fallback DNS Servers: 8.8.8.8 8.8.4.4

Link 2 (enp4s0)
Current Scopes: LLMNR/IPv4 LLMNR/IPv6
     Protocols: -DefaultRoute +LLMNR -mDNS +DNSOverTLS DNSSEC=yes/supported

Link 14 (wg-mullvad)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS +DNSOverTLS DNSSEC=yes/supported
Current DNS Server: fc00:bbbb:bbbb:bb01::1
       DNS Servers: 10.64.0.1 fc00:bbbb:bbbb:bb01::1
        DNS Domain: ~.
```

it looks like DNS over TLS is enabled for the wg-mullvad interface, and I guess Mullvad's DNS servers do not support that protocol. Manually disabling it with `resolvectl dnsovertls wg-mullvad no` helps until reconnect.

**Comment by pinkisemils** [comment]
It used to be the case that `systemd-resolved` [didn't] expose a method on it's DBus interface to change DoT config for links. However, I checked out what's available on Fedora 34, and the functionality is there now. So I'll probably just call this method during setup to ensure we're not using DNS over TLS. 

We do have public DoT servers, but that's besides the point - the app first needs to work properly so that these servers are reachable :slightly_smiling_face:.
