### ISSUE TITLE
Exclude hosts

### ISSUE THREAD

**Issue by Shadow505** [mullvad/mullvadvpn-app#2902]
Hi,

I decided to switch from another VPN provider to Mullvad and it mostly looks good. It does however look like that there is one crucial feature missing: Excluding hosts.

What I need: Exclude specific domains (that was possible at the previous VPN provider) or at the very least specific IPs, so that they will bypass the VPN.

I saw that there is a split tunneling feature - that does however not provide me with an option to exclude specific domains or IPs. Excluding specific apps is not suitable for this case.

Are there plans to support this in the future? And until then: Is it possible to set this up through config files? I found a reference to a "AllowedIPs" parameter, I do however not know in which file that is located and how I would use it in my case.

Without this I would not be able to use the VPN, I therefore hope that there is a solution

I am running the **Linux version**.

Thanks!

**Comment by pinkisemils** [comment]
We don't have in-app support for this, but it is a feature that has been considered before. However, if you're using Linux, there's always a way. Due to the way we do policy based routing, you can set up firewall rules that will effectively rely on the same rules that our split tunneling feature relies on. For that, you'll need to have `nftables` installed. The rule just has to apply the connection tracker mark with the value of `0x00000f41` and the meta mark to ` meta mark set 0x6d6f6c65`. You can type the rules directly into the standard input of `nft`, but you can also just save them to a file and load them with `nft -f $pathToRules`. These rules have to be applied once per boot. To remove the rules, you'd have to just remove the table you've added, and if you're using the example below, it would be `nft delete table excludeTraffic`. 

```nft
define EXCLUDED_IPS = {
    173.239.79.196,
    173.239.79.197,
    17.0.0.0/8
}

table inet excludeTraffic {
  chain excludeOutgoing {
    type route hook output priority 0; policy accept;
    ip daddr $EXCLUDED_IPS ct mark set 0x00000f41  meta mark set 0x6d6f6c65;
  }
}
```

**Comment by Shadow505** [comment]
Hi,

thanks, that works. Would be great to have in app support for this in the future.

I am assuming that there is currently no way to whitelist specific domains? Whitelisting the IPs works as long as they are static, unfortunately often a CDN is being used and this therefore won't work.

And a small note: The correct delete command appears to be: `nft delete table inet excludeTraffic`

**Comment by pinkisemils** [comment]
Thanks for the correction. Split-tunneling based on DNS will require us to run our own resolver, and we have considered this. Currently, there are no plans to implement it, but we will have a custom resolver for helping with insane behavior on macOS.

**Comment by Shadow505** [comment]
So you're saying that with the release of the custom resolver, there would be a way to achieve domain whitelisting? 

If so, any idea when it would be available? Just a rough estimate if possible.

**Comment by pinkisemils** [comment]
The custom resolver will be a macOS specific feature. There are no plans for domain based split tunneling for now.

**Comment by Shadow505** [comment]
Oh okay, I see. Hoping that the IP based split tunneling will be available via the GUI in the near future.

Thanks your your time!

**Comment by Kinrany** [comment]
Is this something you'd accept as a contribution?

**Comment by faern** [comment]
> Is this something you'd accept as a contribution?

Do you mean for Linux specifically? Probably not at the moment. It would be a huge feature to implement and we probably can't accept ownership and maintainership of a huge external feature like that.

We have work going on internally (still) to integrate our own resolver in the app on macOS. When that is done we can evaluate if it makes sense to extend that to Linux and use it for per domain split tunneling.
