### ISSUE TITLE
[Feature request] Context menu for systray icon

### ISSUE THREAD

**Issue by onchov** [mullvad/mullvadvpn-app#2959]
I've seen https://github.com/mullvad/mullvadvpn-app/issues/471, but:
1. Every time you connect/disconnect, you have to close the app window afterwards. That makes 3 clicks (as opposed to 2 with a traditional context menu, where it disappears after choosing an item).
2. Not everyone is a fan of big fonts and colours and design cues generally taken from mobile devices. It would be great if those users had a choice.

FWIW, I'm logging this mainly with the Windows app in mind. On my Linux machine Mullvad's GUI is disabled and I only use it through CLI.

Please kindly reconsider the request.

**Comment by raksooo** [comment]
@onchov When the setting "Unpin app from taskbar" is enabled we show a context menu when the tray icon is right-clicked. You can find the setting near the bottom in _Settings_ -> _Preferences_. When the app is pinned to the taskbar we don't allow that since the app is intended to act like a context menu.

**Comment by onchov** [comment]
Thanks @raksooo, I won't have access to my Windows machine for a while now to verify, so closing by your word.
