### ISSUE TITLE
Mullvad Repository for apt install mullvad-vpn

### ISSUE THREAD

**Issue by Danrancan** [mullvad/mullvadvpn-app#3049]
## Issue report

Operating system: <ubuntu 20.04>

App version: <Latest -->

### Issue description

I cannot find a known apt repository to add mullvad to my app repos. I would like to automatically install and update mullvad with the command `apt install mullvadvpn` on ubuntu 20.4, and include that package in my updates when using `apt update`. Is there a repository for mullvad that I can add to automatically download and install the package instead of using gdebi for a manual installation?
![Screenshot_20211019_183318](https://user-images.githubusercontent.com/30222551/138004660-25f9fc61-4ddd-4e27-8943-d1960b76b77b.png)

**Comment by faern** [comment]
We want to provide more methods of installation. We want to eventually add this type of repository. But I have no ETA for this. Let's leave the issue open for tracking this "feature".

**Comment by faern** [comment]
It is not a priority for us right now. So in the long run pretty good chances, in the short term: Very low chances sadly.

**Comment by Danrancan** [comment]
> It is not a priority for us right now. So in the long run pretty good chances, in the short term: Very low chances sadly.

How hard is it to actually set up a mullvad.net ppa and just run it off of the current mullvad.net servers? Wouldn't this be a relatively easy task?

**Comment by Danrancan** [comment]
> We want to provide more methods of installation. We want to eventually add this type of repository. But I have no ETA for this. Let's leave the issue open for tracking this "feature".

Glad it is in the long-term plan. This would make things much easier for linux users.

**Comment by sunjam** [comment]
fyi #524 is also an open issue for more general Flatpak support across all distributions.  There is even a free Mullvad key offered to anyone who can make it happen.  Cheers.

**Comment by Danrancan** [comment]
> > How hard is it to actually set up a mullvad.net ppa and just run it off of the current mullvad.net servers? Wouldn't this be a relatively easy task?
> 
> No PPA, just a regular repo. Not everyone uses Ubuntu or derivatives. In my opinion, only a regular repo makes sense. In the case of packages for Debian, you will cover more distributions (including Ubuntu)

Gotcha.

**Comment by d4f5409d** [comment]
> It is not a priority for us right now. So in the long run pretty good chances, in the short term: Very low chances sadly.

I installed the app via a .deb file and it would be useful to me to update Mullvad together with my system instead of every time redownloading the .deb package. Vivaldi does somehow let you update it with the system even if it is installed as a .deb.

**Comment by faern** [comment]
> This information needs to be made more visible on the [download page](https://mullvad.net/en/download/vpn/linux)

We are working on it. The download page will eventually reflect the repositories. As soon as the web team has the time ;)

> Will Mullvad Browser also be available in this repo?

Yes that's the plan. Eventually. We just need to figure out some details about signing and other stuff.

> What is the best practice to use a repository version of an app if I already have a working version manually downloaded?

Will probably work slightly different on different distros. I think it should work fine to just add the repository and install via the package manager right away. But I would still recommend uninstalling the package first and then adding the repository and installing it again, to be sure it works smoother. **Don't forget to copy your account number and other important info before uninstalling**.

I'm closing this as completed since the repositories are now live.

**Comment by Victor239** [comment]
@faern there's no `mantic` release, yet this has been the current Ubuntu release for 2 months now.

**Comment by faern** [comment]
> @faern there's no `mantic` release, yet this has been the current Ubuntu release for 2 months now.

Thanks. We were working on preparing for that, but forgot the last step. Currently adding it in #5550.

**Comment by faern** [comment]
Our apt repository servers now have support for Ubuntu 23.10, Mantic.

**Comment by erebion** [comment]
Did you consider making this part of Debian so that it just gets adopted by all the distributions?

**Comment by d4f5409d** [comment]
Linus, will the deb work on other Ubuntu derivatives like Pop! OS or Zorin OS, or only on Ubuntu and Debian?

**Comment by faern** [comment]
> Linus, will the deb work on other Ubuntu derivatives like Pop! OS or Zorin OS, or only on Ubuntu and Debian?

We only test the app on Debian, Ubuntu and Fedora. Our supported distributions can be seen on the [download page](https://mullvad.net/download/vpn/linux) and in a bit more details in our [github repository](https://github.com/mullvad/mullvadvpn-app/#platformos-support) or in [this FAQ entry](https://mullvad.net/en/help/search?q=debian#41). In this case supported == tested. Prior to releasing any app we do internal quality control and leak tests etc. These are only performed on the supported distributions.

However, we don't actively prevent the app from being installed on other non-supported distributions. We know for a fact that people use our app on non-supported distributions. But we can't guarantee the security there since we don't test it in any way. So I can't recommend using the app on those distributions, but in practice it will likely work OK most of the time :shrug:

**Comment by adrelanos** [comment]
> Will Mullvad Browser also be available in this repo?

* https://github.com/mullvad/mullvad-browser/issues/133
* https://github.com/mullvad/mullvad-browser/issues/201

**Comment by faern** [comment]
> At this point, however, an instruction for less advanced users would be useful, describing how to lie to $(lsb_release -cs). With proper warning, of course, at your own risk.

The troubleshooting section in the install guide outlines this exact error and case already. The guides are owned by the support team, so improvement suggestions are best directed to support@mullvad.net
