### ISSUE TITLE
DNS gets superseded by router default

### ISSUE THREAD

**Issue by xioren** [mullvad/mullvadvpn-app#3139]
## Issue report

Operating system: Debian 5.14.16-1

App version: 2021.6 

### Issue description

When connected to a network that has a router level DNS setting, the Wireguard DNS gets put on the bottom of the list of DNS servers in resolv.conf. The result is "Temporary failure in name resolution" errors and no usable internet.

resolv.conf before connecting to Mullvad:

```
# Generated by resolvconf
search hsd1.wa.comcast.net
nameserver 1.1.1.1
nameserver 1.0.0.1
nameserver 2001:558:feed::1
nameserver 2001:558:feed::2
nameserver 2606:4700:4700::1111
nameserver 2606:4700:4700::1001
```
after connecting:
```
# Generated by resolvconf
search hsd1.wa.comcast.net
nameserver 1.1.1.1
nameserver 1.0.0.1
nameserver 2001:558:feed::1
nameserver 2001:558:feed::2
nameserver 2606:4700:4700::1111
nameserver 2606:4700:4700::1001
nameserver 100.64.0.3
```

both:
```
nameserver 1.1.1.1
nameserver 1.0.0.1
```
and
```
nameserver 2606:4700:4700::1111
nameserver 2606:4700:4700::1001
```

are set at the router level.

I know there is a limit to the number of servers that can be utilized in resolv.conf and I'm quite sure the Mullvad DNS tacked on to the end of the list is over the limit and ignored. Putting the Mullvad DNS at the top of the list manually solves the issue.

**Comment by pinkisemils** [comment]
There is no good way to work around this. You could try using `systemd-resolve`, which allows per-interface configuration, and it supports DNS over TLS which can help with ISPs that do DNS hjiacking. You can also set an [environment variable](https://github.com/mullvad/mullvadvpn-app#environment-variables-controlling-the-execution) to force a particular way to manage DNS. You'll probably want `/etc/resolv.conf` to be managed via static file until we figure out a more optimal solution here. 

Ultimately, this is due to the fact that we try very hard to err on not screwing with user's config, thus maybe you'd be interested in not using our in-tunnel DNS resolvers. If you were to set 1.1.1.1 and 1.0.0.1 as custom resolvers via `mullvad dns set custom 1.1.1.1 1.0.0.1`, your DNS queries will still be routed through our tunnel. Of course, you have to be aware that you won't be using our resolvers in this case, which may or may not be desirable.

**Comment by xioren** [comment]
That's unfortunate. While I'm aware of ```systemd-resolve``` I don't yet know much about it (assuming it is a different service than that which populates resolv.conf) and certainly from a security standpoint, having the user modify how DNS resolution is handled while connected rather than Mullvad makes me uneasy and opens up greater possibility of incorrect set up and DNS leaks. Obviously the ideal solution is it is all handled by Mullvad but I understand the way DNS resolution is handled on Linux leaves a lot to be desired. I guess for a temporary stop gap, I will have to try setting a custom DNS. Can ipv6 resolvers be set with ```mullvad dns set custom```?

**Comment by pinkisemils** [comment]
If you just want to use Mullvad resolvers, then the easiest thing for you would be to set the `TALPID_DNS_MODULE` environment variable by changing the unit file for our daemon via `systemctl edit mullvad-daemon` and adding the following
```systemd
[Service]
Environment="TALPID_DNS_MODULE=static-file"
```
>... certainly from a security standpoint, having the user modify how DNS resolution is handled while connected rather than Mullvad makes me uneasy and opens up greater possibility of incorrect set up and DNS leaks. 

Regardless of how you configure your DNS settings, unless you've specified custom local DNS config in the app, will always go through the tunnel, and our firewall rules ensure that the only our resolver will be reachable in the default config, or if a custom resovler is set, then only that resolver will receive DNS traffic.

>Can ipv6 resolvers be set with mullvad dns set custom? Is it necessary? I have ipv6 tunneling enabled.
Yes, they can be set, no it shouldn't be necessary.
