### ISSUE TITLE
Upgrade from 2021.4 to 2021.6 fails

### ISSUE THREAD

**Issue by mxve** [mullvad/mullvadvpn-app#3160]
## Issue report

Operating system: Windows 10 Pro 64-Bit, 21H1, Build 19043.1348

App version: 2021.4, 2021.6

### Issue description

Upgrading from 2021.4 to 2021.6 failed with the following error:
```
---------------------------
Mullvad VPN Setup
---------------------------
Failed to uninstall a previous version. Contact support or review the logs for more information.
---------------------------
OK   
---------------------------
```

This was caused by the uninstaller failing at completly uninstalling the application.
- ```C:\Program Files\Mullvad VPN``` still existed but was empty
  - Manually deleting the directory failed because it was locked for being in use, no setup/mullvad process was running.
- Registry entry under ```HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall``` wasn't removed
  - Manually deleting the registry entry for Mullvad resolved the issue and 2021.6 installation worked without further issues

Issue has been reported in the app with a link to this issue.

**Comment by mvd-ows** [comment]
Thanks for reporting this issue. We'll review the logs included with the problem report and get back to you.

**Comment by mvd-ows** [comment]
Log files turned out to not have much useful information in this case.

The most likely reason is that some unrelated application had an open handle to the installation folder. This can happen e.g. if you're using `cmd` and `cd` into a folder. When doing so, one or more handles are created and this prevents the folder from being removed.

Good thing you managed to solve it.

We'll be looking into adjusting the logic and error messages involved in handling this failure case.
