### ISSUE TITLE
[Log4J Mitigation temporary Feature Request] Switch button to block/unblock LDAP port in the tunel

### ISSUE THREAD

**Issue by BirdInFire** [mullvad/mullvadvpn-app#3207]
Like Everyone know here Log4j is a very very bad problem actually ans many of us (since it use LDAP as way to propagate) have blocked in their router (UDM pro in mine) this protocol (to and from internet, and to and from local network).

To Reduce the risk of a (not patched for now) software to use this i would like to ask a temporary Switch in advanced to block these port through the VPN too.

(The time Dev mitigate all Vulnerable Software).

For the switch (if you accept to do it) i propose LDAP disabled by default (and like the local network one) enable it to let LDAP port work into the tunnel.

Finaly i say again i ask for this feature as a TEMPORARY feature, to protect your userbase only for some month the time to let dev who is slower (or understaffed) to fix their system.

**Comment by faern** [comment]
You already have a competent firewall built into your OS. I suggest you use that to block said port instead.

This is not a flexible firewall app intended to be used in the way you describe. Given our (and most) software release procedure this type of solution is not very flexible and would be very slow. We are not going to be releasing anything more this year due to Christmas coming up etc. The earliest we will have a new release is mid January. And by then most people have hopefully upgraded their Log4j. If not, they should still block it in their firewall software, not their VPN software.
