### ISSUE TITLE
Subcommands are not correctly suggested in zsh

### ISSUE THREAD

**Issue by carbongreat13** [mullvad/mullvadvpn-app#3305]
## Issue report

Operating system: macOS 10.15.7
App version: 2021.6
Shell: zsh 5.7.1 (x86_64-apple-darwin19.0)
 
### Issue description
If you type mullvad relay set tunnel and press Tab, the subcommand will be suggested as follows.
`help       -- Prints this message or the help of the given subcommand(s)`
`openvpn    -- Set OpenVPN-specific constraints`
`wireguard  -- Set WireGuard-specific constraints`
However, the subcommand `help` does not actually exist. The correct one is `--help`.

**Comment by faern** [comment]
Ah.. This is either a bug in `clap` or we configured it invalidly. But `clap` is responsible for generating the shell completions. Since the completion error is quite minor I don't think we'll look into this now. But we should upgrade to `clap 3` in a not too distant future. With some luck, this is automatically fixed there.
