### ISSUE TITLE
Allow me to disable the kill switch!

### ISSUE THREAD

**Issue by ph00lt0** [mullvad/mullvadvpn-app#3430]
## Issue report

Operating system: MacOS 12.2

App version: 2022.1

### Issue description

The app now tells me the kill switch cannot be disabled anymore. This is a big problem for me as I sometimes need to use other VPN services. How do I get around this? 
I really like the kill switch feature, but why limit people by not allowing us to turn it off? This is very unpractical.

**Comment by faern** [comment]
Nothing regarding the kill switch has changed in the last release. The only thing we did was to add information to the GUI informing users that the functionality is there and is always active. We have been quite plagued in the past by users and reviewers not understanding we have a kill switch with no visible setting for it and then they ruled us out as not having any kill switch. So we added this to show that we indeed have a kill switch.

![screenshot_2022-03-17_23-43-13](https://user-images.githubusercontent.com/332294/158906242-8ccb67b4-56d2-44d7-862e-3795bbd71422.png)

From your description I can guess that you are talking about the `Always require VPN` setting under the advanced settings?

![screenshot_2022-03-17_23-44-45](https://user-images.githubusercontent.com/332294/158906368-eb1c94ec-e1d0-4b08-a39f-e618a5d5a2f1.png)

Yes, some people also call this the kill switch, which is not really correct. The kill switch (that can't be turned off) is the inherent design of the app that automatically protects against leaks during sudden tunnel breakage and similar. On the other hand the `Always require VPN` setting is a feature that protects against leaks when the **user has explicitly disconnected**. In other words, enabling `Always require VPN` is only for users who want to only toggle between the two network states "Send everything through Mullvad" and "I don't want my device to be connected to the internet at all".

If you want to sometimes use Mullvad but sometimes disconnect Mullvad and use the internet directly or through another VPN provider, then I suggest you don't enable the `Always require VPN` setting.

**Comment by faern** [comment]
You can read more about these things in our documentation available in this repository: https://github.com/mullvad/mullvadvpn-app/blob/master/docs/security.md#kill-switch

**Comment by ph00lt0** [comment]
@faern I think you should update the text in the kill switch section of the app. This was really not clear to me. I eventually uninstalled the app to get around this...

**Comment by ph00lt0** [comment]
The text really makes it sound like you can't disable mullvad.

**Comment by ph00lt0** [comment]
Disabling the kill switch and quiting the app always allowed me to connect to other vpns. The change therefor feels to me like I could not anymore. But thanks for your help and reply

**Comment by faern** [comment]
@ph00lt0 Do you have a suggestion for how we should describe the `Always require VPN` setting then? Maybe we should remove it. Because **that setting is not the kill switch, but many people keep confusing it with that**. Even without `Always require VPN` on, our app will make sure you are not leaking if the tunnel goes down (unexpectedly) or if our software unexpectedly crashes. That is already protected against **by default**.

* **Kill switch** - Built in by design, not possible to turn off and has never been in our app. This design makes sure that from the moment you hit "Secure my connection" in the app, nothing will leave your computer except encrypted VPN traffic to our servers until the moment when you explicitly and willingly hit the red "Disconnect" button. This kill switch makes sure that users can rely on them being in charge of when things should go in the tunnel vs when they should use the internet normally.
* **Always require VPN** - This very special setting was added because a few users said "hey, I only ever want to use Mullvad or not reach the internet at all. If I'm not on Mullvad I want to be offline! Can you add functionality so that when I disconnect from Mullvad my entire network is blocked instead of unlocked?". This is a very special setting that does not fit for the use case you have where you want to sometimes use Mullvad and sometimes use something else to reach the internet.

**Comment by ph00lt0** [comment]
I would just suggest to add something to the kill switch description saying "if you look to disable Mullvad, make sure always require VPN is disabled under advanced settings". That would have helped me a lot!

I was indeed confused about the difference as many other VPN apps (and i believe yours did aswell) call the always on kills switch or combine it to some sort. I really like the always require vpn feature, but just need to disable it once in a while to get access to some networks.

**Comment by ph00lt0** [comment]
Thanks for considering and implementing the feedback, it's really appreciated!

**Comment by faern** [comment]
Thanks for the feedback. @ph00lt0, may I ask why you have the `Always require VPN` setting enabled? What's your use case? I'm just trying to understand the various use cases for it and how our users use it.

> I was indeed confused about the difference as many other VPN apps (and i believe yours did aswell) call the always on kills switch or combine it to some sort

Neither our kill switch or our extra `Always require VPN` feature has changed in a very long time. The only thing we did was to now add more information to the GUI about the otherwise invisible "kill switch design". We did this because we had many users who either 1) thought we did not have a kill switch or 2) thought that `Always require VPN` was the kill switch.

We have discussed this internally and we will likely move the `Kill switch`-information button added in `2022.1` from preferences into advanced. That way both the Kill switch and `Always require VPN` items will be visible at once, and we hope it will be more obvious that they are two separate things.

**Comment by ph00lt0** [comment]
@faern I sometimes have to use networks I don't fully trust, nor have ownership of, when using them I keep always require VPN on just to be sure. When at home trying to connect to some servers for which I need vpn I turn it off, this doesn't really bother me tbh. I think the addition of the kill switch info just confused me, that it couldn't be disabled anymore.

**Comment by faern** [comment]
> I keep always require VPN on just to be sure

You really don't need to! Unless you are afraid that you might accidentally slip and hit the disconnect button in our app. That's what `Always require VPN` protects against: Making sure you don't leak to the internet after having willfully disconnected the VPN.

Our always-on built in `Kill Switch` will take care of not leaking to the untrusted networks as long as our app is in the secured mode. Meaning *at all times* from when you press "Secure my connection" until you press the "Disconnect" button. Including if our system service crashes etc. All of this is "for free", not needing you to enable any settings at all.

> that it couldn't be disabled anymore.

It never was possible to disable *that* kill switch. I see your confusion. But the feature the new information refers to was always there and has never been possible to turn off.

**Comment by ph00lt0** [comment]
@faern I believe I do as sometimes Mullvad doesn't reconnect correctly because of issue #2477 
I get your point tho, but generally I just prefer to be on the safe side. 

Thanks for all the replies :)

**Comment by acrostich** [comment]
I also have set `Always require VPN` to be on the safe side, which doesn't seem to be needed or helpful from the discussion above.

In addition to move the `Kill Switch` information to the Advanced section, you may want to make it more consistent with the other settings - even though it is not a setting per se. For instance you could have it just under `Always require VPN` with a green dot on the right, i.e. a similar indicator to show it's on as per the other settings, but different in that it can't be slid to off as there's no off, and a short explanation underneath.

It would be helpful to also update https://mullvad.net/en/help/search/?q=kill+switch to explain how it contrasts with the Always require VPN` setting. I.e., don't mention one without refering to the other as it is helpful to under each, to understand both.

**Comment by marcitqualab** [comment]
Hello I think that there might be a bug in the latest version 2022.1 on Linux. 

Expected on app running:
1. Deactivate the switch "Settings/Advanced/Always require VPN"
2. Disconnect the secure connection
3. Internet is working without VPN.

Actual:
On step 3. Internet is blocked. 

Internet only works when the app is running and a secure connection is activated.
When the app is not running or the secure connection is deactivated internet is blocked. 
Activating or deactivating the switch  "Settings/Advanced/Always require VPN" does not have any effect.

**Comment by faern** [comment]
That is really strange. Please list all firewall rules with the command `sudo nft list ruleset`. When `Settings/Advanced/Always require VPN` is enabled, there should be a lot of Mullvad rules in there, but when it's disabled they should not exist.

```
table inet mullvad { ..... }
table ip mullvadmangle4 { ..... }
table ip6 mullvadmangle6 { .... }
```

If those tables go away when you disable the setting, there is some other issue going on. Check if your routing table is correctly set up? `ip route`

**Comment by deftoner** [comment]
I came here for the exact same thing, I was using mullvadvpn 24/7 but a place was blocking the connection so I needed to disable it. Kill Switch text REALLY sends the wrong information I wasted 20 minutes searching from my phone to find out that it has nothing to do with the "Requiere vpn" thing. all other vpn clients, kill switch works as the requiere vpn on mullvadvpn and the text does not help.

**Comment by MinightDev** [comment]
> Thanks for the feedback. @ph00lt0, may I ask why you have the `Always require VPN` setting enabled? What's your use case? I'm just trying to understand the various use cases for it and how our users use it.
> 
> > I was indeed confused about the difference as many other VPN apps (and i believe yours did aswell) call the always on kills switch or combine it to some sort
> 
> Neither our kill switch or our extra `Always require VPN` feature has changed in a very long time. The only thing we did was to now add more information to the GUI about the otherwise invisible "kill switch design". We did this because we had many users who either 1) thought we did not have a kill switch or 2) thought that `Always require VPN` was the kill switch.
> 
> We have discussed this internally and we will likely move the `Kill switch`-information button added in `2022.1` from preferences into advanced. That way both the Kill switch and `Always require VPN` items will be visible at once, and we hope it will be more obvious that they are two separate things.

is there any way to revert the `always require vpn ` option because i enabled it without knowing what it does and when i wanted to remove mullvad from my computer i couldn't reach the internet anymore, so im stuck now is there any solution please?

**Comment by faern** [comment]
Uninstalling the app should remove any blocking rules. But maybe we have a bug there. Can you please tell me which version of the app you had installed and on which operating system?

You can install the app again and toggle the setting on and off in order to remove the blocking rules I think. Then you can uninstall it again. Depending on your platform.

**Comment by marcitqualab** [comment]
> Hello I think that there might be a bug in the latest version 2022.1 on Linux.
> 
> Expected on app running:
> 
> 1. Deactivate the switch "Settings/Advanced/Always require VPN"
> 2. Disconnect the secure connection
> 3. Internet is working without VPN.
> 
> Actual: On step 3. Internet is blocked.
> 
> Internet only works when the app is running and a secure connection is activated. When the app is not running or the secure connection is deactivated internet is blocked. Activating or deactivating the switch "Settings/Advanced/Always require VPN" does not have any effect.

Late update, sorry, I do not remember the details of how I fixed it. I think I reverted to a previous version. I was using Ubuntu 20.04. I am now on a new machine and version 2022.1 with Linux ubuntu 22.04 is working fine.

**Comment by faern** [comment]
@pouriamoosavi Could you please elaborate on why you need there to be no firewall rules blocking non-VPN traffic? And in what states exactly? While the app is connecting? When the tunnel is established? It would greatly help us in our design if we understand why certain users need certain behavior.

The app will inject new firewall rules on every state change. So the command `sudo nft flush ruleset` will only "help" temporarily, and I'm not sure when you run it.

**Comment by pouriamoosavi** [comment]
I need to route my IP addresses directly in these scenarios:

I have three docker containers that have their own virtual network on 172 IP range. 
I want to have access to my local IP addresses and my router IP address.
I want to have access to my office VPN and my office IP. My office is not on the other side of the planet so it makes more sense to connect there without passing through Mullvad.

And also your are correct. After every reconnect I have to flush the `nftables` again. But I didn't find it that hard as long as it fixed above problems.

**Comment by faern** [comment]
> I want to have access to my local IP addresses and my router IP address.

Did you try enabling the "Local network sharing" setting? This should allow access to all private/non-routable IPs. This setting is supposed to do what you want here.

> I have three docker containers that have their own virtual network on 172 IP range.
> I want to have access to my office VPN and my office IP. My office is not on the other side of the planet so it makes more sense to connect there without passing through Mullvad.

If you are technically savvy enough to know about `nft` you can fix this with custom firewall rules, not by *removing* rules, but by adding rules. We have a guide on how you can craft and add nftables rules that will allow certain IP ranges and whatnot to bypass the VPN: https://mullvad.net/en/help/split-tunneling-with-linux-advanced/

**Comment by Jesuszilla** [comment]
This change is very bad because you HAVE to disable the VPN to log into Facebook! Let us disable it temporarily like we used to be able to!

**Comment by faern** [comment]
This issue is not about a change, but a misunderstanding. Nothing has changed. It was never possible

**Comment by FrustrumCode** [comment]
I just got bit by this trying to prep my laptop pre-flight.  The mullvad app saying giving it's won't connect to internet message because it was disconnected, and then jumping to settings and seeing the kill switch and trying to disable it (I looked for the always on from memory and failed to find it.)

My suggestion would be to pair these settings, and move the always on out of advanced.  That would be the most natural to avoid confusion, group settings that interoperate together.

Another solution would be just have a link "disable always on to allow connecting to the internet" in the "won't connect to internet" message.   Clicking the link jumps you to the advanced setting.

Thanks for a great product.

**Comment by faern** [comment]
> My suggestion would be to pair these settings, and move the always on out of advanced. That would be the most natural to avoid confusion, group settings that interoperate together.

They are already paired. Please upgrade to the latest release. The advanced menu is even gone, and both the kill switch info and the lockdown mode (yes, we renamed it) is under "VPN settings":

![screenshot_2022-11-22_11-05-24](https://user-images.githubusercontent.com/332294/203285926-b3aa6a89-ad5e-4887-a16a-ec38a602894f.png)

**Comment by faern** [comment]
If you don't have "Lockdown mode" enabled, then no, being disconnected from Mullvad means Mullvad does not in any way interfere with your network.

**Comment by DutchPete** [comment]
@faern can you please explain why the kill switch toggle is disabled? Why even have a toggle button? It is misleading, to say the least, because it suggests something that is not possible therefore serves no purpose. After all, what is the problem to enable the toggle? Why not, what is preventing you guys from doing that?

I find it rather paternalistic to decide for the user that it should always be on, whereas I would like to decide for myself.

The concept of the kill switch is explained, and that is fine, but what is not fine is this, quoting from your documentation:
> **If the tunnel were to come down and your operating system tries to route packets** out via the normal network rather than through the VPN, **these rules would block them from leaving**. So rather than failing open, meaning if the tunnel fails your traffic leaves in other ways, we fail closed, meaning if the packets don't leave encrypted in the way the app intends, **then they can't leave at all**.

That is precisely what worries me: I lose control over my computer. I cannot accept Mullvad hijacking my computer's internet access if the tunnel fails.

I like Mullvad's basic concept, and am using both the browser and the VPN, which work hand-in-glove, and everything runs smoothly. Well done 👍 However, a disabled kill switch toggle will be a dealbreaker for me if that does not change.

**Comment by faern** [comment]
> Why even have a toggle button? It is misleading, to say the least

Others might disagree. This is very subjective. The disabled "toggle" was added somewhat recently. All the years up until we added it was full of confused people who did not think we had any kill-switch at all, because they could not find anything in the UI named kill-switch. We got tons of reviews and articles about our app that stated as a fact that we did not have any kill-switch. All of this was not true. It was built into the core design of the app from day one. We wanted to make it clear to our users that we indeed have an always-on kill switch. So they would more clearly understand how the app worked. We could have just added an information label of some sort. But we figured that a "read only setting" was probably the most intuitive (most users don't read pure information text, they look for settings).

> After all, what is the problem to enable the toggle? Why not, what is preventing you guys from doing that?

We have not really explored in detail what work it would entail to allow disabling the kill-switch. But it would for sure require us to re-think a few things around firewall rules etc. And it all comes at the risk of introducing issues that makes the app less safe for the users who want the kill-switch (the vaaast majority).

> That is precisely what worries me: I lose control over my computer. I cannot accept Mullvad hijacking my computer's internet access if the tunnel fails.

Can you explain why you want the kill-switch to be off? On a more practical level, rather than an idealistic level. To me it sounds like what you want is "Make my computer use Mullvad as much as possible, but I also don't care if it is not using Mullvad really". If you have working internet on your computer when Mullvad breaks down for whatever reason. Why do you prefer your traffic to temporarily not be encrypted while Mullvad re-establishes a new tunnel, as it does automatically. Compared to have a temporary internet downtime, reconnect back and be sure everything leaves through the VPN.

We see it the opposite of how you see it. We give control and assurance back to users that they previously did not have. When they click "Secure my connection" in our app, they should be able to feel assured that their traffic won't leak until they explicitly disconnect the VPN.

Our main goal and target user group is privacy and anti-censorship. For this user group it's kind of crucial to not randomly leak packets outside the tunnel, since that could compromise exactly what Mullvad is there to protect for them.

**Comment by DutchPete** [comment]
@faern many thanks for your detailed explanation. Below are my views about some of the points you make.

> All the years up until we added it was full of confused people who did not think we had any kill-switch at all, because they could not find anything in the UI named kill-switch.

You are conflating visibility and togglability. If you make the kill switch togglable it will not be any less visible than it is now.

> But we figured that a "read only setting" was probably the most intuitive

It is not any more intuitive than any of your other togglable settings. You could make the default setting ON, and allow those users who do read pure information text to decide for themselves.

> And it all comes at the risk of introducing issues that makes the app less safe for the users who want the kill-switch

I am not arguing against having a kill switch.

> We give control and assurance back to users that they previously did not have.

Except where the kill switch is concerned, where you have actually taken away control from the user.

> When they click "Secure my connection" in our app, they should be able to feel assured that their traffic won't leak until they explicitly disconnect the VPN.

Yes, of course, but a togglable kill switch does not change that. That is why a default ON setting is easiest and safest for those who don't want to tune settings.

> Can you explain why you want the kill-switch to be off?

If Mullvad can establish a new tunnel, that is fine. But how long does it take to do so? Most of the time it will be quick, but there might be situations where it is more problematic and will take longer. It is precisely those situations (taking longer than normal to establish a new tunnel) I am worried about because during that period I will not have internet access and I have no way to unblock Mullvad's stranglehold on my computer.

> "Make my computer use Mullvad as much as possible, but I also don't care if it is not using Mullvad really".

That is a contradictory statement, and if however it were true, there would not even be any point in using Mullvad.

> For this user group it's kind of crucial to not randomly leak packets outside the tunnel

If you aim for that, you should consider a firewall, togglable of course.
[Quote from the Windscribe site](https://windscribe.com/features/firewall):
“A firewall is a superior solution to a "kill switch". The "kill switch" is a snake oil feature and offers absolutely zero protection because it's a reactive measure. Between your VPN disconnecting and the program detecting that it did, packets can leave your computer over the default gateway (your ISP). A firewall blocks ALL connectivity outside of the tunnel. If the VPN connection drops, there is nothing that needs to be done, and not a single packet can leave the machine, since the firewall will not allow it. In geek terms it fails closed.”

**Comment by faern** [comment]
> That is why a default ON setting is easiest and safest for those who don't want to tune settings.

This is wrong. This is neither the easiest nor the safest.
* The *easiest* for the developers is to do nothing - keeping current functionality
* The *easiest* for the user is to have fewer options - Don't conflate flexibility and ease of use
* The *safest* for users is to have the kill-switch on - Leaking traffic is never *safer*, only maybe more convenient at times for some users.
* The *safest* for users is whatever breaks the least often - See argument about bugs below

My main point about there being a risk of allowing to disable the kill-kill switch is around potential software bugs. More settings and more flexibility around core safety features introduce more complexity and more code paths. With more complexity in the code the risk of bugs increases. If the code has less alternative paths to take and all developers always can assume "when secured, no traffic should leave the computer unencrypted" they are less likely to introduce bugs that make traffic leak when the kill-switch is *on*.

> I will not have internet access and I have no way to unblock Mullvad's stranglehold on my computer.

You can just disconnect Mullvad. You make it sound like your computer is held hostage and there is nothing you can do to stop us from blocking traffic. You can just disconnect/cancel the new connection attempt. We only hold your network tight as long as you tell us to.

**Comment by faern** [comment]
> [Quote from the Windscribe site](https://windscribe.com/features/firewall): ...

Yes! Feels like I have to describe this over and over so many times over the years. I agree with Windscribe here. We don't have an old style snake oil kill-switch that is reactive. Our "kill-switch" is implemented using the firewall and it's protecting from leaking a single packet. If you read our [security documentation on our kill-switch feature](https://github.com/mullvad/mullvadvpn-app/blob/main/docs/security.md#kill-switch) you see that we also really dislike calling it a kill-switch. For the same reason as Windscribe!

In the old days of VPNs, before they got good, no app had any kill-switch. Then some clients started adding it in the reactive snake oil approach that reacted to a broken connection and tried to stop leaks as fast as they could. This way of course sucked. But the terminology "kill-switch" was really established. Of course such snake oil was not good enough for Mullvad, and we designed our app from the ground up to proactively tightening the firewall and ensure nothing ever leaks until the user explicitly disengage the VPN. There was not really any good terminology for the safety features/level we had, so we just sort of called it a "privacy preserving VPN client". This resulted in users emailing us and reviews being posted, mostly claiming we don't have any kill-switch and that our client is insecure.

After a few years of these false and confused information floating around we decided to bend to the pressure and call our proactive firewall protection a "kill-switch" since that was the established terminology for sort of this functionality.

Why we never made it configurable was because it was simpler, safer and virtually no demand for the opposite. Over the years we have integrated with thousands of confused users who think we don't have a kill-switch, but almost zero users who actually want to leak traffic in the reconnect state.. Because that's essentially what it is. Disabling the kill switch would allow traffic to leak while reconnecting the tunnel.

This in turn enables a huge attack vector. An attacker can use any of many ways to trigger a VPN tunnel reconnect, and then you start leaking. Depending on the position and capability of the attacker it can be trivial to make a VPN disconnect. And then you start leaking, so they can scoop up your traffic.

**Comment by faern** [comment]
> What firewall? I don't see one mentioned in the settings.

The one built into your OS. On macOS, which you seem to be using, that's [PF (Packet filter)](https://en.wikipedia.org/wiki/PF_%28firewall%29). On all desktop platforms our app communicates with the platform's built in firewall, and in the secured state of our app (when you have explicitly engaged Mullvad) we apply rules in the existing firewall to ensure traffic flows as it should. All these rules are cleared when you disconnect/disengage Mullvad.

> OK, so just to be absolutely sure: if, during a tunnel failure I want Mullvad to stop protecting my computer, I can just right-click on the icon in the menu bar (I am on macOS), then click on Disconnect and my computer is free. Correct?

Exactly, of course! You should at any time be able to disengage Mullvad from securing your computer. Is this not working for you, or have you not tried?

**Comment by DutchPete** [comment]
OK, good to know Mullvad interacts with my firewall. Thanks for clearing that up.

> or have you not tried?
I have tried and it works. The only situation I have not been able to check it is when the tunnel goes down. But I shall take your word that it works in that situation too.

Thanks a lot for your detailed explanation AND for your patience with a satisfied but PITA user 😀

Good work for the VPN AND for the browser, which I am also using and works hand-in-glove with the VPN.

**Comment by killa1333** [comment]
> > That is why a default ON setting is easiest and safest for those who don't want to tune settings.
> 
> This is wrong. This is neither the easiest nor the safest.
> 
> * The _easiest_ for the developers is to do nothing - keeping current functionality
> * The _easiest_ for the user is to have fewer options - Don't conflate flexibility and ease of use
> * The _safest_ for users is to have the kill-switch on - Leaking traffic is never _safer_, only maybe more convenient at times for some users.
> * The _safest_ for users is whatever breaks the least often - See argument about bugs below
> 
> My main point about there being a risk of allowing to disable the kill-switch is around potential software bugs. More settings and more flexibility around core safety features introduce more complexity and more code paths. With more complexity in the code the risk of bugs increases. If the code has less alternative paths to take and all developers always can assume "when secured, no traffic should leave the computer unencrypted" they are less likely to introduce bugs that make traffic leak when the kill-switch is _on_.
> 
> > I will not have internet access and I have no way to unblock Mullvad's stranglehold on my computer.
> 
> You can just disconnect Mullvad. You make it sound like your computer is held hostage and there is nothing you can do to stop us from blocking traffic. You can just disconnect/cancel the new connection attempt. We only hold your network tight as long as you tell us to.

This is just your laziness and because of this, most people from Russia now cannot use your VPN for which they paid money, since your servers are blocked with us and I can’t even use shadow socks or other proxies to connect to your servers because  impossibility of disabling the kill switch.

**Comment by DutchPete** [comment]
@killa1333: thanks for bringing up this issue. I was not aware of it.

You present another argument for making the kill switch togglable. @faern explained the non-togglability as follows:

> Why we never made it configurable was because it was simpler, safer and virtually no demand for the opposite. Disabling the kill switch would allow traffic to leak while reconnecting the tunnel. This in turn enables a huge attack vector.

I did state:
> I find it rather paternalistic to decide for the user that it should always be on, whereas I would like to decide for myself.

But after that I did not argue further with that, although it now transpires that, like me, you would like to decide for yourself whether the kill switch is on or off. **And that is how it should be.** The kill switch is shown as a togglable option, but in reality that is misleading people, it is make-believe, because it is not what it *appears* to be.

So, I now realize that the reason given for non-togglability was not a good enough reason. In fact, is that really the reason, or is there another one we are not told about?

**Comment by faern** [comment]
Please explain how disabling the kill-switch would solve your problem in Russia. Because I do not understand how that would help the situation.

**Comment by jordanss1** [comment]
Ok so there is no longer an **Always require VPN** option in the settings. I am a new user as of today and it's frustrating because everytime I pause the connection for whatever reason, my internet goes down. The kill switch is literally forced. 

There must be a way to disable the kill-switch. Otherwise that's just ridiculous.

**Comment by killa1333** [comment]
> Please explain how disabling the kill-switch would solve your problem in Russia. Because I do not understand how that would help the situation.

To connect to your servers I need to use a third-party proxy, and kill switch always blocks it when I start trying to connect to your servers

**Comment by jordanss1** [comment]
Just read that lockdown mode is the new Always Require VPN. Lockdown mode has been disabled since I downloaded this app, yet every time I disconnect from Mullvad my internet is blocked.

**Comment by DutchPete** [comment]
@jordanss1: how do you “pause” the connection? I only see “Disconnect & quit”?
Doing the latter does no block my internet - I have Lockdown mode disabled.

**Comment by jordanss1** [comment]
@DutchPete sorry I should have said Disconnect. Your internet is not blocked when you disconnect? That's weird because anytime I disconnect my connection is blocked. 

Even when re-connecting to Mullvad it says "BLOCKING INTERNET" while reconnecting the VPN and then once connected the internet works again.

**Comment by DutchPete** [comment]
@jordanss1 nope, it does not do that to me. I can disconnect and reconnect without any problems.

But, like I stated in an earlier comment above, it worries me what would happen if the Mullvad tunnel would suddenly collapse: would my internet connection be hijacked? @faern convinced me that would not be the case, but now with your shenanigans, and to a lesser extent those of @killa1333,  I am not so convinced anymore.

I have 2 more days left on my subscription, and if there is no clear commitment to resolve this, or if the resolution is to leave kill switch untogglable, then I will not renew my subscription.

**Comment by jordanss1** [comment]
@DutchPete  hey man I'm confused by what you mean. So are you getting the typical kill-switch behaviour where if you disconnect from the VPN you can no longer use the internet?

I don't understand how a VPN company doesn't even offer their own users the ability to choose if they want to have the VPN toggled. That's ridiculous. So if I go to a banking or online shopping website on my laptop I literally have to delete the Mullvad app in order to access sites that block VPNs. If this isn't a bug and is just a part of how Mullvad operates that's pretty ridiculous. I think I kight get my money back to be honest.

**Comment by jordanss1** [comment]
Ok I have no idea why but my issue has been resolved and for some reason the VPN is now allowing me to disconnect without killing my internet. I am happy.

Will update is this changes. Seems like some weird bug though.

**Comment by MrChocolatine** [comment]
> Your internet is not blocked when you disconnect? That's weird because anytime I disconnect my connection is blocked.

Same here, I don't have any problem. I have the "Lockdown mode" disabled and I can perfectly browse the Internet whether I am connected to Mullvad or disconnected.

> I don't understand how a VPN company doesn't even offer their own users the ability to choose if they want to have the VPN toggled. That's ridiculous. So if I go to a banking or online shopping website on my laptop I literally have to delete the Mullvad app in order to access sites that block VPNs. If this isn't a bug and is just a part of how Mullvad operates that's pretty ridiculous. I think I might get my money back to be honest.

If you want so much to disable the kill-switch, then just disconnect the VPN... But again, apparently you have issues with your installation or with your Internet connection, don't necessarily blame Mullvad for that. Your situation clearly indicates you have a problem, and obviously this is not a normal behaviour and how their VPN works.

**Comment by jordanss1** [comment]
> > Your internet is not blocked when you disconnect? That's weird because anytime I disconnect my connection is blocked.
> 
> Same here, I don't have any problem. I have the "Lockdown mode" disabled and I can perfectly browse the Internet whether I am connected to Mullvad or disconnected.
> 
> > I don't understand how a VPN company doesn't even offer their own users the ability to choose if they want to have the VPN toggled. That's ridiculous. So if I go to a banking or online shopping website on my laptop I literally have to delete the Mullvad app in order to access sites that block VPNs. If this isn't a bug and is just a part of how Mullvad operates that's pretty ridiculous. I think I might get my money back to be honest.
> 
> Of course this is not a normal behaviour and how their VPN works.
> 
> If you want so much to disable the kill-switch, then just disconnect the VPN... But again, apparently you have issues. Your situation clearly indicates you have a problem with your installation or with your Internet connection, don't necessarily blame Mullvad for that.

Thanks for your response. I think it was a weird bug because now it is working as it should. I am happy though and you're right I shouldn't have jumped the gun.

**Comment by DutchPete** [comment]
@MrChocolatine
> If you want so much to disable the kill-switch, then just disconnect the VPN...

Nope, that is not disabling the kill switch, that is disabling the VPN.

**Comment by MrChocolatine** [comment]
@DutchPete 

> Nope, that is not disabling the kill switch, that is disabling the VPN.

Which... Disables the kill-switch.

Since it has been clearly explained it cannot be disabled in any other way.

**Comment by DutchPete** [comment]
@MrChocolatine 

> Since it has been clearly explained that it cannot be disabled when the VPN connection is active.

It cannot be disabled at present the way Mullvad VPN is coded. That does not mean it cannot be done, as @faern wrote to me:

> Why we never made it configurable was because it was simpler, safer and virtually no demand for the opposite.

So, the coding can be changed, it is just that the devs don't feel like it, it is too much of a hassle, for them.

**Comment by MrChocolatine** [comment]
You seem to take turns, continuing messages by answering different things.

I was answering to Jordan.
Right now, to disable the kill-switch you have to disconnect from the VPN. That's it. That's their philosophy.

> It cannot be disabled at present the way Mullvad VPN is coded. That does not mean it cannot be done,

Absolutely nobody said the opposite, everything is possible.

**Comment by MrChocolatine** [comment]
Anyway, the discussion goes round in circles.

**Comment by faern** [comment]
I have yet not heard any clear use-case for a disabled kill-switch. All I have heard are misunderstandings about what the kill-switch currently is, and unrelated bugs that made the app not behave as intended.

> To connect to your servers I need to use a third-party proxy, and kill switch always blocks it when I start trying to connect to your servers

This is the only sort-of use case I have seen. But this should not be solved by disabling the kill-switch, this should be solved by split tunneling. If you want one specific program (your proxy) to go outside the tunnel, it should use split tunneling. If you "disable" the kill-switch as a way to make arbitrary programs go outside the tunnel, what prevents other programs from leaking then? It has to be explicit what programs are allowed outside the tunnel (split tunneling).

What platform are you on? If you are on macOS, I'm sorry, since we don't yet have split tunneling there. It's in the backlog, but currently not ready.

**Comment by killa1333** [comment]
> I have yet not heard any clear use-case for a disabled kill-switch. All I have heard are misunderstandings about what the kill-switch currently is, and unrelated bugs that made the app not behave as intended.
> 
> > To connect to your servers I need to use a third-party proxy, and kill switch always blocks it when I start trying to connect to your servers
> 
> This is the only sort-of use case I have seen. But this should not be solved by disabling the kill-switch, this should be solved by split tunneling. If you want one specific program (your proxy) to go outside the tunnel, it should use split tunneling. If you "disable" the kill-switch as a way to make arbitrary programs go outside the tunnel, what prevents other programs from leaking then? It has to be explicit what programs are allowed outside the tunnel (split tunneling).
> 
> What platform are you on? If you are on macOS, I'm sorry, since we don't yet have split tunneling there. It's in the backlog, but currently not ready.

Windows. Adding shadow socks to whitelist doesn't help

**Comment by faern** [comment]
> Windows. Adding shadowsocks to whitelist doesn't help

Then there is a bug in split tunneling, or you are using it wrong in some way. The exact use case of split tunneling on windows is to be able to add specific exe files that will be able to communicate outside the tunnel. Are you sure you added the correct exe file? Have you been in contact with support@mullvad.net? Either way, this is not related to the kill-switch, but just a problem with split tunneling.

**Comment by Bang1338** [comment]
I have a same major problem here:

After uninstalled Mullvad, internet access (for LAN) is no more. Only Wifi work.

**Comment by faern** [comment]
@Bang1338 This sounds like a bug with the uninstall process. However, we can't debug with the little information you provided. Please try starting your computer and see if that helps. If the problem persists, please contact support@mullvad.net and state what operating system you use, what version of the app you had installed and describe what you did.

**Comment by Bang1338** [comment]
> If the problem persists, please contact [support@mullvad.net](mailto:support@mullvad.net)

Thank, I managed to fix it with this option (thank Windows)
![image](https://github.com/mullvad/mullvadvpn-app/assets/75790567/514af220-c5c3-4193-a300-0eada2d0b1a1)
