### ISSUE TITLE
Workaround for enabling the mullvad-daemon service on Sysvinit

### ISSUE THREAD

**Issue by Aixata** [mullvad/mullvadvpn-app#3488]
Operating system: Devuan 4 Chimaera with Sysvinit
App version: 2022.1

`/etc/init.d/mullvad-daemon.sh` >
```
#!/bin/sh
### BEGIN INIT INFO
# Provides: mullvad-daemon
# Required-Start:   $syslog $local_fs 
# Required-Stop:    $syslog $local_fs 
# Should-Start: $network 
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
# Short-Description: Mullvad VPN daemon
### END INIT INFO

. /lib/lsb/init-functions
prog=mullvad-daemon
PIDFILE=/var/run/$prog.pid
DESC="Mullvad VPN daemon"
start() {
    log_daemon_msg "Starting $DESC" "$prog"
    start_daemon -p $PIDFILE "/opt/Mullvad VPN/resources/mullvad-daemon" -v --disable-stdout-timestamps
    if [ $? -ne 0 ]; then
        log_end_msg 1
        exit 1
    fi
    if [ $? -eq 0 ]; then
        log_end_msg 0
    fi
    exit 0
}

stop() {
    log_daemon_msg "Stopping $DESC" "$prog"
    killproc -p $PIDFILE "/opt/Mullvad VPN/resources/mullvad-daemon"
    if [ $? -ne 0 ]; then
        log_end_msg 1
        exit 1
    fi
    if [ $? -eq 0 ]; then
        log_end_msg 0
    fi
}

force_reload() {
    stop
    start

}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    force-reload)
        force_reload
        ;;
    restart)
        stop
        start
        ;;

    *)
        echo "$Usage: $prog {start|stop|force-reload|restart}"
        exit 2
esac
```
The space in the folder name isn't recognized because of the way the start_daemon function is written. Wrap in double quotes the 3 instances of `$exec` in the start _daemon function of `/lib/lsb/init-functions` 

`sudo chmod +x /etc/init.d/mullvad-daemon.sh`

`sudo update-rc.d mullvad-daemon.sh defaults`

`sudo reboot`

I know that support for other distros and other init systems aren't a priority, but if I may suggest to replace the space in the Mullvad VPN by a dash or underscore to increase overall compatibility and avoid issues like these and #2904.

**Comment by faern** [comment]
Thanks for the init script. We could consider adding it to the app even if we don't officially support any distro where it would be used. But a problem with that is that we have not verified if the app works in a satisfactory way without leaks. So it's a bit dangerous to make it look like it's supported.

Regarding the space in the path. It's there because `electron-builder` decided so. If we change it now it's going to cause a lot of churn in existing scripts, installations, guides and whatnot. So this is not something we will do unless we have a very good reason. I'm sorry, but I don't consider a *bug* in sysvinit, an init system we don't support, to be compelling enough to cause a lot of trouble for existing users.

I actually see the space as a great way to make distros and other maintainers find and clean up their issues. Unless they have documented that spaces are prohibited it is definitely a bug if they don't, so they should fix it.

**Comment by Aixata** [comment]
I wouldn't expect this to be officially supported, especially that it's probably a small minority of people even attempting to use the  app over the official instructions to go with wireguard/openvpn configs on unsupported distros. My main intention was to have this info in a proper location for anybody researching trying to make it work like I did. 

Surprisingly `init-functions` is part of base linux. It's just very unfortunate that the old shell script contained that oversight, I wouldn't call it a bug with sysvinit itself. I did successfully run the tests on `browserleaks.com` and `dnsleaktest.com`. I would expect it to run as well as on supported debian distros since aside from the way the service is kept alive, devuan is just a debian fork, but if there are more tests you would like me to run if you ever plan to support it I would be happy to help.

It's a fair argument regarding keeping the space, these are pretty isolated cases anyway.

**Comment by carbongreat13** [comment]
SysVinit is obsolete software; it is better to use modern software like OpenRC or Runit.

**Comment by MarkusPettersson98** [comment]
Thanks for your contribution @Aixata! We currently have no plans on supporting SysVinit-based systems, so I'll close this issue for now. You could always open a feature request if this is something you would like to see, even if I don't see us doing this anytime soon :blush:
