### ISSUE TITLE
Add a switch "Block all" for the DNS blocking lists

### ISSUE THREAD

**Issue by MrChocolatine** [mullvad/mullvadvpn-app#3691]
## Issue report

Operating system: macOS Monterey v12.4

App version: 2022.1

### Issue description

In the `Preferences` view, above the existing switches `Block ads / trackers / malwares`, would it be possible to add a switch `Block all` so we can block/unblock all the lists at once?

<img width="432" alt="02 preferences" src="https://user-images.githubusercontent.com/47531779/175152371-2ac842dd-d7fe-4f93-b2d7-d0629cd8f0d0.png">

Thank you.

**Comment by faern** [comment]
Hi. Thanks for the suggestion. Is this because you toggle it so often than it becomes tedious to click all three? Or what's the issue you are currently having? I think we imagine users mostly touching these settings once or a few times, and then leaving them like that. If you want to block ads, you probably always want to block ads.

With the latest release of the app we added two more block lists: Adult content and gambling. With a total of five lists I agree that it becomes even more "tedious" to click all of them, BUT it also becomes less likely that someone would want all of them on. With a wider assortment of block lists in various categories it's more likely that any given user only want a particular subset of them, not all on or all off. With that in mind, I don't think a general all on/off button makes much sense. But the designers can look at this.

As a work-around if you want to toggle everything often, you can use the CLI to script turning your desired block lists on or off. Have it run `mullvad dns set default` to disable all blocklists and `mullvad dns set default --block-ads --block-trackers --block-malware` to turn them on.
