### ISSUE TITLE
2 suggestions about the Linux GUI

### ISSUE THREAD

**Issue by logan2k** [mullvad/mullvadvpn-app#3700]
## Issue report

Operating system: Debian 11

App version: 2022.2

### Issue description

I have suggestions about the Linux GUI:

1. Remove the animation (Or at least add an option to toggle it).
The animation is not only annoying for some users, but also use significant GPU time while active.

2. Some options/features are only available to CLI, please consider add them to GUI. Examples:
mullvad relay set location any
mullvad obfuscation set mode auto
mullvad tunnel wireguard key rotation-interval set

**Comment by faern** [comment]
> * Remove the animation (Or at least add an option to toggle it).
>   The animation is not only annoying for some users, but also use significant GPU time while active.

Thanks for the suggestion. I can forward it to the designers.
 
> * Some options/features are only available to CLI, please consider add them to GUI. Examples:

In general, most features we add start out in the CLI. There they sit and cook for a few versions so we can test it out and get some feedback from a few users who try it out. Then we add it to the GUI when we feel it's stable enough and if it's a feature we think GUI users will be interested in. But some settings are too niche to ever end up in the GUI.

>   mullvad relay set location any

We don't believe too many users will want a completely random server selection. Since it can have you end up in places with really high latency. So we have not added that. Why do you prefer this over setting a specific country, if I may ask?

>   mullvad obfuscation set mode auto

This is a very new feature. And it is definitely going into the GUI rather soon. It was recently added and was sort of experiment feature. Up until recently it was only available on 10 WireGuard servers. So it would not have made sense to have it in the GUI up until now. In the last few weeks we have been desiging how this should look in the GUI, and it will be added sometime later this year.

>   mullvad tunnel wireguard key rotation-interval set

We don't believe most users will want to change this interval. And having the interval set too low will mess with peoples' connections (a key rotation triggers a reconnect also), so we don't want to expose it so people get themselves into too much trouble.

May I ask what rotation interval you prefer and why you believe that is better than the default seven day interval?

**Comment by logan2k** [comment]
Thank you very much for the detailed reply!

> Why do you prefer this over setting a specific country?
For getting over censorship. Sometimes it never connect on manual location(even if the location works previously), but on full random, leave it for a while and it will eventually success.
I think it's better to add this options anyway, because people who like to stick on fixed location can still do it...

> May I ask what rotation interval you prefer and why you believe that is better than the default seven day interval?
This is not mandatory, but I just think it's good for security to set it shorter.
Even the CLI is limiting to 24 hours shortest, but personally I would like to set it to something like 4-6 hours. If you can loose the CLI limit, it would also be nice.

Thanks again.
