### ISSUE TITLE
[Wireguard Tutorial Update]

### ISSUE THREAD

**Issue by Disrooting** [mullvad/mullvadvpn-app#3704]
This isn't an issue to me, but for some other users it might be. I find the Wireguard setup on router is really old and outdated, newest OpenWRT is 22.03 which is still a RC, but it comes with a lot of changes, so some users will pretty much find it a bit confusing if they're trying to use the VPN on an OPENWRT router. I really hope that you guys could take some time and change that or i could just take a few screenshots of me setting it up and you can update it then give credit to the work i've done. Reply here if you're interested and i'll be more than happy to help.

Regards

**Comment by faern** [comment]
Hi. Thanks for the feedback and heads up that newer OpenWRT have significant changes! However, our guides are not managed by our app team, and this repository is about the app specifically. I'll forward this issue link to our support and guide folks. In the future I recommend you contact support@mullvad.net directly for website and guide related issues and feedback

However, since It's in the middle of the summer and many are on vacation here in Sweden, non-critical support issues such as updating guides, will likely be a bit slow. Just keep that in mind :)

I'm going to close this as it's not tracking any app issue/feature.

Regards
