### ISSUE TITLE
Server reconnect on key change

### ISSUE THREAD

**Issue by vvaadim** [mullvad/mullvadvpn-app#3777]
## Issue report

Operating system: Debian 11.4 Stable

### Issue description

It would be nice to re-connect to the same server you were previously connected to on Key Rotation in wireguard(it does not do that on choosing an entire city)

Example;
Change your VPN server region to some city(mullvad will choose a server itself from a given city) -> rotate your wireguard key -> re-connect to the exact same server you were previously connected to

**Comment by faern** [comment]
Can you explain in more detail why you want that behavior? Thanks

**Comment by vvaadim** [comment]
> Can you explain in more detail why you want that behavior? Thanks

I personally have my wireguard auto-rotation set to 24h, its a little bit annoying getting a new IP out of nowhere after a key migration. I know the default timer is 7 days or something, however my threat model does not allow me to store it for that long on the server. It would be nice if we were able to reconnect to the same server after key rotation, I'm pretty sure it would also save some nerves for other people even tho they are using the default timer. Having the same IP after key-rotation might also have some more minor advantages like IP correlation threat based on time.

**Comment by faern** [comment]
> its a little bit annoying getting a new IP out of nowhere after a key migration

This won't be fixed by connecting back to the same relay. Our relays have multiple exit IPs and you are assigned one of these depending on your wg pubkey. So when you rotate the key, you are very likely to get a new exit IP even if you stick to the same server. This is why we have not bothered with sticking to the same server. Because your connections would break anyway and you would get a new exit IP anyway.

Please also mind that picking a new relay can be good for privacy in some threat models. Continuously changing where you route your traffic.

Would you be willing to share what, more exactly, it is that your threat model does not allow to "store"? They WireGuard key material? You might be interested in trying out our Post Quantum secure tunnels experiment. Even if you don't need quantum resistant encryption, it has the added benefit that it uses a new wg key on every new connection, but keeps the same in-tunnel IPs and exit IPs. So this sounds like what you want. Unless it's important for you that the in-tunnel IP is also rotated, which requires a traditional wg key rotation. https://mullvad.net/en/blog/2022/7/11/experimental-post-quantum-safe-vpn-tunnels/

**Comment by MarkusPettersson98** [comment]
@vvaadim Hi again,

This is not something that we are planning to do. It would still be nice to understand your threat model better, and if using Post Quantum secure tunnels could help in your case. Post Quantum has been stable for a while now :blush:

I will close this issue due to inactivity if I don't see a response here within a reasonable time frame. All the best :yellow_heart:
