### ISSUE TITLE
Admin rights

### ISSUE THREAD

**Issue by glottis0q** [mullvad/mullvadvpn-app#3812]
## Issue report

Operating system: Windows 10

App version: x

### Issue description

I would like to install mullvadvpn on my work computer but I dont have admin rights. Would it be possible to install it or run it without admin rights or from a usbstick?

**Comment by Evernow** [comment]
I don't believe this is possible on Windows

**Comment by faern** [comment]
Sorry, but the app really must run as administrator. The app is designed around the idea of securing the entire device. This includes editing device global firewall rules, manage DNS settings, routing table etc. All of this require the process to be run as an administrator. The app would not be close to being able to uphold its security guarantees otherwise. So no, it's not and will not be possible.

**Comment by glottis0q** [comment]
Got that.

**Comment by glottis0q** [comment]
Thanks for explaining
