### ISSUE TITLE
[Feature request] Remove uppercase letters and spaces from the installation path

### ISSUE THREAD

**Issue by carbongreat13** [mullvad/mullvadvpn-app#3836]
## Issue report

Operating system: Arch Linux

App version: 2022.3

### Issue description

Currently, on Linux, it is installed in `/opt/Mullvad VPN`.
However, a directory containing uppercase letters and spaces is against Unix tradition.
I suggest changing it to `/opt/mullvad-vpn`.

**Comment by faern** [comment]
Are you having an issue with the current directory name, other than esthetics only?

Please see my answer to the same thing over here https://github.com/mullvad/mullvadvpn-app/issues/3488#issuecomment-1091638793.

Tradition and standard are two different things. We are not going to do something just because it's/has been common. If we'll do it it's because it's recommended or required. But as long as it's not prohibited, it's a bug in **other software** to not handle it well.
