### ISSUE TITLE
Changing of a wireguard tunnel MTU doesn't change actual wg-mullvad interface MTU.

### ISSUE THREAD

**Issue by lessneek** [mullvad/mullvadvpn-app#3839]
## Issue report

Operating system: Fedora 36

App version: 2022.3

### Issue description

Changing of a wireguard tunnel MTU doesn't change actual wg-mullvad interface MTU.

**Comment by faern** [comment]
Thanks for reporting this. We found it ourselves just after making the release. This has been fixed on `master`, but we forgot to backport it to the release branch. Sorry about that. It will be fixed in the next release. I can't give any ETA for that yet though.

**Comment by lessneek** [comment]
Why don't you just release a hotfix 2022.3.1? It is a mean of a few minutes. I've got unworking VPN with wireguard on my connection. Router drop packets with `too big` response.

**Comment by faern** [comment]
We don't do patch releases in the sense of `<year>.<version>.<patch>`. But we could release `2022.4`. We'll look into this compared to test and release everything in `master`. The latter would also be good since we have a bunch of new nice stuff. But it requires more testing.

> It is a mean of a few minutes

Sadly, our release procedure is not that simple. It takes a few hours. And we always release for all desktop platforms even if there are just changes for one. So it's a bit cumbersome.

Sorry for the inconvenience. Consider using OpenVPN in the meantime.

**Comment by faern** [comment]
We just released version 2022.4. It has this bug fixed. Please upgrade :)
