### ISSUE TITLE
version 2022.3 not compatible with portmaster

### ISSUE THREAD

**Issue by dkakkep601** [mullvad/mullvadvpn-app#3842]
## Issue report

Operating system: Windows 10

App version: 2022.3

### Issue description

Using portmaster with the version 2022.2 of the mullvad app was working fine until I installed the version 2022.3

After installing the whole internet was not working but the mullvad app was connected with wireguard. Restarted my pc and the issue persisted. Portmaster required to put 127.0.0.1 in mullvad's custom dns section to work. Tried removing the custom DNS but still didn't work. Tried changing MTU did not work. Changed servers and did not work. Tried openvpn and it did not work. 

Downgraded to 2022.2 and it worked

**Comment by qbfmjcc687** [comment]
They changed their DNS code so you have to add the DNS (127.0.0.1) in the windows 10 adapter settings

Control Panel\Network and Internet\Network and Sharing Center ---> change adapter settings ---> right click ethernet and choose properties ---> double click ipv4 and add the DNS

**Comment by Broeckelmann** [comment]
The same happens with 2022.4
Then why are they keeping the custom dns option in the settings?
Also in my opinion this is worse and very inconvenient compared to before. :(
But thanks for letting us know 👍. Should have been mentioned in the Release notes in my opinion.

**Comment by tudjnoh986** [comment]
> The same happens with 2022.4 Then why are they keeping the custom dns option in the settings? In my opinion this is very inconvenient compared to before. :( But thanks for letting us know 👍. Should have been mentioned in the Release notes though.

This is really inconvenient because the mullvad adapter doe not remember what I chose when I change servers. The ip 127.0.0.1 has to be inputed manually each time there is a server change or computer restart. I hope they fix this

**Comment by faern** [comment]
Having our app setting DNS on the physical interfaces on your computer proved too error prone. There were a large number of issues related to doing so. We figured that most people who are technical enough to fiddle with DNS probably know how to set it on their adapters anyway. So we stopped forcing DNS settings on Windows.

We still need the setting because we need to know which DNS you want to use. Just because you have set `x.y.z.1` on your physical interface does not mean you want to use it. You could still want to use our in-tunnel DNS. We need to know exactly which IP to unblock in the firewall (we have *very* strict rules around where DNS is allowed). In a future version of the app we will make this simpler by just having the Custom DNS setting be this tri-state toggle:

* Use in-tunnel DNS (the default)
* Unblock all local/LAN DNS
* Use this specific DNS server: [user inserting DNS IP required]

**Comment by faern** [comment]
I'm going to close this since you found a solution. Sorry for not communicating this clearer when releasing `2022.3`
