### ISSUE TITLE
Separate login credentials for each and every Windows user/account

### ISSUE THREAD

**Issue by ivadham** [mullvad/mullvadvpn-app#4049]
## Issue report

Operating system: Windows 10 21H2

App version: 2022.5

### Issue description

On a single Windows device, there may be several Windows user accounts. The issue is that when Windows user **A** logs in using their Mullvad account number, Windows user **B** finds their own Mullvad app already logged in with **A**'s login number. Apparently, Mullvad for Windows uses the same credential for every user on the same Windows device, which is utterly weird!

**Comment by faern** [comment]
This is by design. That is because the VPN is a system wide service and not a per-user service. The VPN protects and absorbs all traffic from a machine. Including traffic from all users' processes as well as userless system services. It would not make much sense to have this be per user I'm afraid. Then our app would need to have quite advanced credential handling to makes sure user A can't read user B's account number.

The threat model and security of our app assumes that the entire device it runs on and all users who has access to it are to be trusted.
