### ISSUE TITLE
Mullvad compatible with macOS 13 Ventura?

### ISSUE THREAD

**Issue by bit-blit** [mullvad/mullvadvpn-app#4065]
Operating system: macOS Monterey 12.6

App version: 2022.5

Sorry in advance if this is the wrong place to bring this up, but I can't find this information anywhere else, plus I am not that technical.

Does the current version 2022.5 work on macOS 13 Ventura? Ventura is scheduled for release next week, and I can't find anywhere whether Mullvad VPN is compatible with the new OS release. I checked the official Mullvad site, and it states nothing to confirm this, so I can only conclude that it is NOT ready for Ventura yet.

Many Thanks for your help in advance.

bit-blit

**Comment by faern** [comment]
Our download website for macOS says `Works on macOS Catalina (10.15) or later (64 bit only)`. So that implies that Ventura is supported, because it's newer than `10.15`. Where / in what form would you expect/want such information on the website? Posting a blog post saying that we aim to support the not-yet-released OS seems a bit over the top to me.

Yes, we have tested our app on the Ventura beta releases, and it works.

This type of question is better directed at our customer support at support@mullvad.net. This issue tracker is mostly for bug reports and sometimes feature requests. Thank you.

**Comment by bit-blit** [comment]
You are absolutely correct that the Mullvad website states 10.15 or later, implying that it is compatible with Ventura. I just wanted to double-check with technically minded people as to whether this was the case as I don’t want to update my OS before Mullvad is ready as I consider it an essential piece of software. No harm done.

And no, having a blog post on your site stating that Mullvad VPN is ready for macOS Ventura is not "over the top.” Quite the contrary. My backup software provider made a simple blog post stating that his software was fully ready for the Ventura release - he didn’t seem to think it was “over the top”. It is information that is absolutely relevant, and considering this is a major (not point) OS release, necessary.

Next time, I will use the support email that you provided.

Thank you for your help.

**Comment by bit-blit** [comment]
As a follow-up -

I used the support email @mullvad.net and here is the response I was given:

"Hi,

We have not fully tested it with Ventura yet and some beta users have reported that the Mullvad daemon stops. If possible I would recommend that you wait and install Ventura until Apple has released at least one update for it.

Best regards,

Stefan”

This is conflicting information as to what you provided me with. Who am I to believe - You or Stefan? Not everyone is as technically adept as you, and I was making a simple inquiry. Thank you.

**Comment by faern** [comment]
To my knowledge, the user(s?) who had issues got them automatically resolved in later Ventura betas. It's quite common that our app misbehaves in at least one of the betas, but that Apple fixes that issue before the final OS release.

It is true that the support team has not run through complete testing of Ventura, but the app team has. We have tested it on at least one beta version. But since the final version of the OS is not out yet, we of course can't guarantee it will work on that one.

Having it work on the latest macOS release is of course a priority for us. So it's quite likely that it will work fine out of the box, and if not, that we will fix it rather fast.

> If possible I would recommend that you wait and install Ventura until Apple has released at least one update for it

I consider this a blanket recommendation, not really related to our app. I personally also usually waits at least a month before adopting a new major OS version. To have the OS vendor and app developers iron out some issues that might exist.
