### ISSUE TITLE
Connecting to openvpn server using talpid

### ISSUE THREAD

**Issue by dutiful-hilly** [mullvad/mullvadvpn-app#4149]
Hello,

I'm unable to find any docs about talpid, how could I use it to connect to an openvpn server using a configuration file?

**Comment by faern** [comment]
If you have a regular OpenVPN config file, you should use the vanilla OpenVPN app/client, not our app. `talpid` is just a privacy preserving VPN *library*, not a program. It does not know what an OpenVPN config file is. Please download OpenVPN if you really want to use config files. https://openvpn.net/community-downloads/

**Comment by dutiful-hilly** [comment]
I do want to use a library instead of a premade Client. Ive looked at the OpenVPN3 library but I have 0 experience with c++ so that would be too hard. How would I be able to initialize the connection state machine?

**Comment by dutiful-hilly** [comment]
Could this be reopened?

**Comment by faern** [comment]
I'm sorry, but we don't really have comprehensive documentation on this since we are the only users of `talpid` really. The interface of `talpid` is not stable, as we do not bump versions and we regularly change it to fit our needs and add features.

What's the reason you don't want to use our app then, all of it, not just `talpid`?

If you want to build something on top of `talpid` I recommend that you check out the code in the `mullvad-daemon` crate, which uses `talpid` to establish the tunnels. However, the interface is not stable, and it's also not well documented except the code itself where we use it.

The separation between `talpid` and `mullvad` is a bit vague. Some Mullvad stuff is hardcoded into the `talpid` layers even if we try to avoid it. The separation partially for separation of concerns. It would currently be too much overhead for us to maintain `talpid` as a stable and well documented library for general use.
