### ISSUE TITLE
Tidy up some macOS behaviour

### ISSUE THREAD

**Issue by Ben2HellAndBack** [mullvad/mullvadvpn-app#4151]
## Issue report

Operating system: macOS 13

App version: 2022.5

### Issue description

First of all - let me tell you how much I love Mullvad. There are a couple of niceties that could make Mullvad VPN feel more at home on macOS

1. Use native network-extensions on macOS (why can we on iOS but not macOS) (I know this is non trivial)
2. Make sure Mullvad has the correct icon & app name in "Allow in Background"

   <img width="502" alt="Screenshot 2022-11-17 at 23 23 35" src="https://user-images.githubusercontent.com/896954/202581905-d80619c8-0da4-4f92-a89d-2e877ace26b3.png">
3. Allow the VPN to run even without the `mullvad-exclusions` group, currently if I remove this group it brick

   <img width="470" alt="Screenshot 2022-11-17 at 23 34 40" src="https://user-images.githubusercontent.com/896954/202582420-3432cfea-dd92-4cb7-ae1c-7a866e26f077.png">

(Happy to try and help out with points 2 or 3)

**Comment by faern** [comment]
1. The native network extension will both be hard for us to implement on macOS and probably not optimal for anyone. The network extension has to be a separate process not running as `root`. It is controlled by the OS and not by us. Since it's not running as `root` it will not be able to modify the firewall rules or do other system wide security configurations we need. On iOS this "works" simply by being the only option available, and there is no way to modify the firewall anyway. We want to keep a much higher security bar on macOS where we can.

2. This is probably because the app is signed with a certificate belonging to Amagicom AB. This certificate has been around for a while. We have been meaning to create a new certificate and move the app to Mullvad VPN AB but has not seen a large need for it. So it has not been prioritized. But it seems like macOS 13 start showing this certificate owner name in more places than was previously available, so maybe it's higher priority now. Although, this is mostly a cosmetics thing. I don't think there is anything you can help out with here. We need to create certificates and reconfigure our build server etc.

3. Is it a problem that we have this group? Why is it a problem? I don't have all the details right now. But I imagine it would be more complex for us to allow the app to work without it. And complexity = risk.

**Comment by ph00lt0** [comment]
@faern how are you guys looking at this in 2026? It seems apple is pushing developers to move of packet filter in favor of their less controlable Network Extensions.

https://developer.apple.com/documentation/technotes/tn3165-packet-filter-is-not-api#Moving-off-packet-filter

**Comment by hulthe** [comment]
@ph00lt0 We're aware on Apples unfortunate stance on packet-filter. We're not currently committed to moving to Network Extensions, but we are investigating the feasibility of doing so **without compromising on security and privacy**. I expect this work to take some time though.

**Comment by ph00lt0** [comment]
@hulthe thanks for getting back! Well we evidently can see your implementation works better than what Apple offers now, I am worried that it might not be possible in the near future. 

I guess we all hope that Apple will make a better killswitch feature available that actually works. 

If you have any insights to share once you concluded your investigation, I would be very interested to hear from you. Feel free to email it to my username @ privacy guides.org.
