### ISSUE TITLE
Login with account number and custom private key

### ISSUE THREAD

**Issue by GibMeMyPacket** [mullvad/mullvadvpn-app#4247]
## Suggestion

Operating system: Windows 10

App version: 2022.5

### Suggestion description
Hello, i guess it was since v2022.5 that Mullvad required creating a new WireGuard key upon login and since then i have few issues with my multi-boot devices or so.
Previously, i was able to login and simply use OpenVPN protocol without creating a new WireGuard key that has 5 limits in total.
But now i have to login and the app tries to create a new Wireguard key even thought I'm willing to use OpenVPN or even if i have another key for the other OS in the device.
With the current logic, If i have two Multi-boot devices with two OS on each, Mullvad app will use 4 slots of my account even thought I'm using Mullvad within two devices.

One possible partial solution could be allowing to login by providing both account number and private key so it doesn't make a new key if the private key is valid. this will partially fix #4072 probably.

**Comment by faern** [comment]
This is a somewhat unfortunate downside of the new way we manage devices. This is intentional and nothing we aim to "fix". Don't think of a "device" as one physical device, but rather a session with Mullvad. If you have the app installed in multiple ways on the same machine each install needs its own identity (session).

It would not make sense to enter the same private key in multiple instances of the app, or to share this "session". Because the app is designed to own its device identifier and it will periodically rotate the WireGuard key. The WireGuard key is an ephemeral secret managed by the app. So it should not be pulled out of the app or used anywhere else, partially because that's a security risk and partially because the app will replace it automatically.

If you have more than five Mullvad apps that you are logged in to, you will need to get two Mullvad accounts.

**Comment by faern** [comment]
For questions regarding or terms of service or payment I kindly advise you to contact support@mullvad.net. This issue tracker is for app bugs and feature requests specifically. And one logged in app install counts as one device in our backend/app.

Having multiple app instances share a single device would be technically complicated as we would either need to invent a way to guarantee they are never active at the same time, or allow them to overwrite each others WireGuard keys and other data and result in a bad user experience.

People who regularly use Mullvad on >5 physical devices should simply have multiple Mullvad accounts, since the TOS states that you can use Mullvad on up to 5 devices. It does not say 5 connections or sessions, but 5 devices. Meaning a phone you have installed Mullvad on and logged in to counts as a device even when it does not have an active VPN tunnel. It counts as a device until you actively log out of the account in the app on that device. And it can be argued that a single physical device dual booted into different OSes counts as multiple devices, it's a gray area I would say.
