### ISSUE TITLE
How to disable GPU rendering on Linux?

### ISSUE THREAD

**Issue by logan2k** [mullvad/mullvadvpn-app#4261]
## Issue report

Operating system: Debian 11

App version: 2022.5

### Issue description
On Debian system with integrated Intel GPU, mullvad GUI use 200MiB RAM, and "--disable-gpu" option have no effect.

**Comment by raksooo** [comment]
If you run the app with `--disable-gpu` (i.e. `/opt/Mullvad\ VPN/mullvad-vpn --disable-gpu`) it should run without using the GPU.

We usually suggest that people use the `--disable-gpu` flag to make the app work with GPUs that Electron doesn't support, not to reduce memory. I did a quick search for this and didn't find any documentation suggesting it. Do you know any resources that suggest using `--disable-gpu` to lower the memory usage?

`--disable-gpu` will probably make animations within the app more choppy.

**Comment by DPTJKKVH** [comment]
@raksooo
>  Do you know any resources that suggest using `--disable-gpu` to lower the memory usage?

#3851 With `nvidia-smi` I can list (among other things) all processes that are currently consuming VRAM and how much. With GPU acceleration disabled mullvad is not shown on that list.

> `--disable-gpu` will probably make animations within the app more choppy.

I hope you don't mind me asking if you know of any actual examples you came across yourself? Because for traveling I use a very ancient device with an Intel Celeron 1.4GHz dual core CPU (no dedicated GPU) that is struggling with normal everyday usage. However, disabling GPU acceleration does not cause any kind of animation issues within the Mullvad GUI application.

If you promise that me doing so will lead to some kind of change (like adding a gpu acceleration toggle to the GUI / disabling GPU acceleration by default / something else) I will go ahead and install the Mullvad GUI on an even more ancient device with an Intel ATOM CPU from 2009 to see if such a device actually shows any kind of animation artifacts when GPU acceleration is disabled.

This is a genuine offer! It is not my intention to be rude or a smartass. I just want to help improve the Mullvad GUI application and based on my experiences, you/the team might have some incorrect assumptions concerning GPU acceleration.

**Comment by pinkisemils** [comment]
We have seen animations degrade on macOS devices when GPU rendering is disabled.
