### ISSUE TITLE
Ability to whitelist networks to not go through VPN

### ISSUE THREAD

**Issue by robd003** [mullvad/mullvadvpn-app#4315]
I would be really helpful to have a section within the app to let you add networks to route over the default gateway instead of using the Mullvad network.

One example is cable modems that are generally on 192.168.100.0/24 if you're connected to Mullvad through the app it will try to connect to that private IP space over the VPN and obviously fail.

**Comment by pinkisemils** [comment]
Which platform in particular are you interested in? This is already possible to do on Linux, following our advanced split tunneling guide.  
Specifically for cable modems though, connecting to private subnets is allowed if you enable LAN access. To access hosts on private networks, you still need to set up routes for the private subnets, if they don't exist. The routes are not needed if the hosts are reachable via your default route normally, without a VPN, but since you essentially have a new default route (for the VPN), the routes become critical for reaching those hosts.
