### ISSUE TITLE
Location Leak on macOS

### ISSUE THREAD

**Issue by Baccount** [mullvad/mullvadvpn-app#4366]
## Issue report

Operating system: macOS 13.2.1 (22D68)

App version: macOS Mullvad 2022.5

### Issue description
Real location is leaked to the FindMy app even when lockdown is enabled, WI-FI is enabled and local network access is disabled. This leaks your real location to family members linked to your Apple ID and Apple sees your real location. 

Reproduce the bug by.
1. Enable location service in macOS and you only need to enable Find My Mac option. "photo below"
2. Enable lockdown and enable WI-FI "Not completely sure if wifi is the cause of leak"
3. Open FindMy app on your iPhone and you should see your real location of your Mac. 

- _Note. if it does not immediately appear in the FindMy app, turn Wi-Fi off and then back on on the Mac seems to cause a location to appear faster._

Photo showing the location setting you need to enable, its enabled by default on macOS
![Screenshot 2023-02-16 at 7 37 47 PM](https://user-images.githubusercontent.com/10781882/219565094-516b14b3-27f0-451f-86a7-29118d19b85a.png)

**Comment by faern** [comment]
To achieve what you seem to want you need to disable FindMy and disable location services overall on your iOS device. Our VPN app does not in any way intend to hide your *location* (as in coordinates obtained from GPS + cellular triangulation). A VPN hides your IP, which is sometimes referred to as location since it can reveal where you are. But these are strictly different. Any app on your device which has the location permission granted can get your precise location and send that off to wherever they want. Be it inside a VPN tunnel or not, your real coordinates will still be transmitted.

For the same reason as if you log into social media using your real name while connected over a VPN, you are not anonymous, you are only hiding where you connect from.

**Comment by faern** [comment]
You might want to look at our privacy guides for a more in depth look into what a VPN does and what other stuff you will need to change in your online habits to protect your privacy: https://mullvad.net/en/help/first-steps-towards-online-privacy/
