### ISSUE TITLE
WG tunnel randomly stops working after a few minutes post pqc exchange, likely malfunctioning security measure.

### ISSUE THREAD

**Issue by ghost** [mullvad/mullvadvpn-app#4397]
When changing keys (http API) and servers via scripts, along with executing the post-quantum exchange binary[1] sometimes seemingly at random a wg interface stops working after some minutes, if it it refreshed using the same method it will again only work for a few minutes.

The only fix appears to be shutting down the tunnel, waiting for a minute or so, restarting the tunnel and redoing the pqc exchange again.

Given the fact that everything works for a few minutes, the implication is that some security measure employed by Mullvad is to blame, likely it thinks that someone is trying to cheat.

The process which triggers the issue seemingly randomly is:

1) fetch wg servers and choose a new one
2)
```
wg set wg0 peer ${OLD} remove
wg set wg0 peer ${NEW} allowed-ips 0.0.0.0/0 endpoint ${NEW_P}
sleep 2
```
3) switch to new new key via curl @ https://api.mullvad.net/app/v1/replace-wireguard-key
4) set wg0 down, flush, set new ip, flush preshared-key, set private-key, link set wg0 up.
5) execute the pqc binary[1] and set the private-key & preshared-key

At this point most of the time everything works fine, but sometimes it triggers the bug. at which point tunnel is functioning for just a few minutes before it stops functioning. Redoing the 5 steps above brings the tunnel back to life, but after a few minutes the problem is repeated.

[1] https://github.com/mullvad/mullvadvpn-app/blob/main/talpid-tunnel-config-client/examples/psk-exchange.rs

**Comment by faern** [comment]
Thanks for reporting this. I'm tagging it as not app related as you are not using the app. I suspect this could be a glitch or too aggressive abuse detection on the server side, but I'm not sure. I have forwarded this issue to our backend service teams.

In the future I recommend reporting issues that are not related to our app directly to support@mullvad.net instead.

**Comment by mvd-ows** [comment]
Are you able to share the full set of scripts being used? Or most importantly, the ones used to drive steps 3-5.

**Comment by jackloomen** [comment]
> Are you able to share the full set of scripts being used? Or most importantly, the ones used to drive steps 3-5.

The full set is somewhat specific to my setup which I would not share, I can share some larger pieces:

```
RELAY_COUNT=$(echo $SELECTION_JSON | jq -s 'length')
echo "relay count: ${RELAY_COUNT}"

RAND_CHOICE_NUM=$(( $RANDOM_NUM % $RELAY_COUNT ))
CHOICE=$(echo $SELECTION_JSON | jq -s '.['${RAND_CHOICE_NUM}']')

echo "random choice #${RAND_CHOICE_NUM}:"
echo $CHOICE | jq

PUB_NEW=$(echo $CHOICE | jq -r '.public_key')
PEER_EP_NEW=$(echo $CHOICE | jq -r '.ipv4_addr_in')':51820'

ip netns exec ${NETNS_NAME} wg set wg0 peer ${PUB_OLD} remove
ip netns exec ${NETNS_NAME} wg set wg0 peer ${PUB_NEW} allowed-ips 0.0.0.0/0 endpoint ${PEER_EP_NEW}

sleep 2

mull-rotate ${NUMBER}
```

mull-rotate:

```
RESULT=$(netns_exec physical -- curl -sSL -X POST \
	-H "Authorization: Token ${ACCOUNT}" \
	-H "Content-Type: application/json" \
	-d '{"old":"'${PUB_OLD}'","new":"'${PUB_NEW}'"}' \
	https://api.mullvad.net/app/v1/replace-wireguard-key)


if [[ "$RESULT" == *"ipv4_address"* ]];
then
	echo "API: Success"
else
	echo "API: Failed"
	exit
fi

IP_NEW=$(echo ${RESULT} | jq -r '.ipv4_address')
```

...

```
ip -n ${NETNS_NAME} link set wg0 down
ip -n ${NETNS_NAME} addr flush dev wg0
ip -n ${NETNS_NAME} addr add ${IP_NEW} dev wg0
ip netns exec ${NETNS_NAME} wg set wg0 peer $PEER preshared-key /dev/null
ip netns exec ${NETNS_NAME} wg set wg0 private-key /path/mullvad/${NUMBER}.priv
ip -n ${NETNS_NAME}  link set wg0 up
ip -n ${NETNS_NAME}  route add default dev wg0

sleep2

mull-pqc-script ${NUMBER}
```

mull-pqc-script

```
PUB_KEY=$(echo ${PRIV_KEY} | wg pubkey)
{ read PQ_PEER_PRIVKEY; read PQ_PEER_PSK;} <<< $(netns-exec $NETNS_NAME -- /path/mullvad-pqc-binary 10.64.0.1 $PUB_KEY)

PQ_PEER_PUBKEY=$(echo ${PQ_PEER_PRIVKEY} | wg pubkey)

PEER=$(cat /path/${NUMBER}_peer.pub)

ip netns exec $NETNS_NAME wg set wg0 peer $PEER preshared-key <(echo $PQ_PEER_PSK)
ip netns exec $NETNS_NAME wg set wg0 private-key <(echo $PQ_PEER_PRIVKEY)
```



*mullvad-pqc-binary  has been trivially modified to output keys without anything else.

**Comment by mvd-ows** [comment]
Thanks. The scripting seems sane at a quick glance. Can you say something about the frequency of running the key rotation?

Is it possible to get some timings for how long the tunnel is working before packets start being dropped at the relay end? If the duration is always exactly the same, or in a small range, it will greatly aid in troubleshooting this.

**Comment by jackloomen** [comment]
Frequency of running the key rotation varies from once a day to possibly within seconds (if a randomly chosen end point is under-performing at the time).

When the issue is triggered, the tunnel is working fine without any issues for 2-5 minutes (it's possible that the time is constant, I just didn't time it) then every packet just appears to be dropped.

**Comment by mvd-ows** [comment]
So the key rotation is initiated manually each time? You could record the output of `date` as a final operation in step 5, then since you're already at the computer just run `date` again if you notice the tunnel is dead.

FYI, the PQ peer is chained to the regular peer used to register/negotiate it, on the individual relay. You can actually switch back and forth between the peers without negotiating PQ again. It would be interesting to know if the regular peer can establish a tunnel when you find yourself stuck with the PQ peer.

**Comment by jackloomen** [comment]
It is manual yes, I will incorporate date output into the script.

> It would be interesting to know if the regular peer can establish a tunnel when you find yourself stuck with the PQ peer.

Not 100% confident but I believe it can. IIRC one of the ways I fixed it before is by shutting down the tunnels (oneshot service), when I start them up again they do not use the PQC peers but the original ones. I think I did not need to refresh the keys to get things to work at that point.

**Comment by mvd-ows** [comment]
Alright, thanks for the update. I have no more suggestions at this time. We'll keep monitoring this.

**Comment by jackloomen** [comment]
It happened again and it was after a reboot (no multiple exchanges in rapid succession). Tunnel worked for 1.5 minutes before failing.

oneshot service started mullvad in non-PQC state, script rotated keys and established PQC state, 1.5 minutes later tunnel fails.

**Comment by jackloomen** [comment]
Next one happened what seems like almost exactly 3 minutes after.

Depending on how fast I noticed it, may add 10-15 seconds to that.

**Comment by mvd-ows** [comment]
We've identified an issue on the relay end, in the logic where it handles peer updates. This has cascading effects for new (e.g. rotated) peers with a linked PQC identity. In effect, the PQC identity is cleaned up prematurely.

A possible work-around is to let the rotated key settle for 10 minutes before upgrading the connection to PQC.

This will be swiftly corrected, but because of the testing required, and also the current release schedule, expect the fix to reach production relays in about 3 weeks from now.

We'd like to thank you for working with us on tracking down this issue. Please contact our support department referencing this thread to finalize the matter.

**Comment by MarkusPettersson98** [comment]
Since it seems to have been resolved on our relays, I'll go ahead and close this issue. Please let me know if you think otherwise and I'll re-open it. Thanks 💛
