### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by krishnacenter** [mullvad/mullvadvpn-app#4663]
Delete

**Comment by tutyfrutti** [comment]
same trouble(

**Comment by vvitad** [comment]
I used this method https://mullvad.net/en/help/windows-openvpn-installation/

**Comment by faern** [comment]
@krishnacenter You are sadly not the only person with this issue. Russia has recently started blocking our API server and the bridges we use to reach it more aggressively. For more in depth help I recommend you contact support@mullvad.net.

In short, basically the ways our app currently access the API are currently blocked. Adding better API obfuscation to the app will take time. You can do a number of things right now to try and make it work:
* Via Tor or some other working proxy service, download a WireGuard config from our website and use vanilla WireGuard instead of our app for the time being. Serbian servers should work quite well still.
* If you have a working VPN tunnel on some other device. Maybe you can share the internet from that device and connect your non-working device through it and make the app able to reach the API in that way.

**Comment by faern** [comment]
I got the following information from our support team. This can be valuable to anyone inside Russia landing on this issue.

If you are logged in to the app but fail to connect, Try to connect to different countries like Serbia, Bulgaria, Denmark, Germany and Switzerland.

If you are not logged in to the app, and fail to do so. You can try to use the WireGuard app instead:

https://mullvad.net/en/help/wireguard-ios/
https://mullvad.net/en/help/wireguard-android/
https://mullvad.net/en/help/wireguard-app-windows/
https://mullvad.net/en/help/wireguard-macos-app/

If you are in Russia then try to connect to different countries like Bulgaria, Denmark, Germany and Switzerland.

If you have a problem to visit our website then change your DNS to 1.1.1.1 or use Tor browser:

https://www.torproject.org/download/
https://onionbrowser.com/

Hope this helps.

**Comment by vvitad** [comment]
@krishnacenter 

Did you use the link I left above?

**Comment by faern** [comment]
Let's keep it for now. Since it is an existing problem for many users. They are more likely to find it if it's open.

**Comment by dizelgerda** [comment]
And if it is technically possible to somehow circumvent these restrictions? Are you planning to do something to resist blocking?

**Comment by addCoffee** [comment]
Hi.
If beta version does't help (2023.4-beta1), try old version - **2021.6** (on 2022.1 I had problems with CPU over 100%)

**Comment by vvitad** [comment]
VPN is now dead for me and for my friends too. Guess

**Comment by StSav012** [comment]
Only the handshake seems to be blocked. As soon as it's completed, the connection stays on.

**Comment by w8noot** [comment]
wireguard | openVPN + shadowsocks | your app and other methods does not work. I've tried most servers and bridges

**Comment by ichimars** [comment]
Got my half-a-year subscription paid over crypto …ed up because of this… No refund, no vpn…That was nice try…🤬
