### ISSUE TITLE
In-app multihop speed reduction?

### ISSUE THREAD

**Issue by mikamidd** [mullvad/mullvadvpn-app#4669]
I'm an occasional multihop user both with the native mullvad app and standalone Wireguard configs and I've noticed that in-app multihop results in lower DL/UL speed compared to the multihop config using standalone Wireguard. 
Same server configuration and other applicable settings, testing against the same speedtest servers.

In-app multihop has about 5-15% lower speed than standalone Wireguard multihop config.
What helps somewhat is reducing the in-app MTU to anything less than 1360 but it's still at least 5% worse on the download and about 10% on the upload than standalone Wireguard. My ISP forces a default MTU of 1480 so maybe it's related to that.
With the standalone Wireguard I can use MTU = 1420 without any issues, and from what I understand 1420 is the maximum that I can use without issues considering the ISP restriction (ISP has no IPv6 so -60 bytes from 1480).
My normal internet connection is 100mbit DL/UL, with both the single-hop VPN **and** Wireguard multihop I get ~90/90mbit on average depending on the server and such which is expected, but with in-app multihop it caps out at about 85 (DL) / 80 (UL).
I understand the inaccuracies of the speed tests and such, but this is something that I can consistently reproduce regardless of the server configuration.

Running Windows 10, app version doesn't matter but currently running 2023.3. 
Is this something particular to how Windows handles networking? Or down to how the app establishes multihop connection? On a somewhat related note the app takes about 10 seconds to establish a multihop connection on my PC which is quite slow and annoying (because killswitch kills the internet connectivity for 10 seconds) unlike the instant Wireguard connection, any plans to make it more robust?

**Comment by faern** [comment]
Those two ways of doing multihop are different and different performance is to be expected. The multihop solution built into the app does cost a bit more performance, but is better at protecting against network analysis attacks.

The multihop solution built into the app puts a WireGuard tunnel inside another WireGuard tunnel. Two layers of encryption, sort of in the same way as the Tor network. This means that when the entry server receives a network packet from you and decrypts it, all it finds inside is an encrypted WireGuard packet and the server it's supposed to be sent to, nothing more. Any attacker observing the entry and exit traffic on the entry server will just see encrypted WireGuard packets, destined to random UDP ports (depending on your app settings)

On the other hand. The multihop offered by our config generator is port based. If you check our server list you'll see that each server has a specific multihop port assigned to it. For example `se-mma-wg-001` has multihop port `3002`. This means that if you speak WireGuard to *any* of our WireGuard relays on port `3002` the traffic will just be forwarded to `se-mma-wg-001` and decrypted there instead. This means that the entry server still can't see the traffic content, BUT any outside observer can see that the encrypted packet is destined for port `3002` and easily figure out that any packet coming in on this port will be forwarded to `se-mma-wg-001` before exiting to the internet. This in turn helps them de anonymize multihop users because it becomes a lot easier to correlate entry and exit traffic on entry relays.

The performance drop can also be caused somewhat by the fact that both tunnels have the same MTU, since they use the same virtual adapter. This can cause excessive fragmentation of the IP packets. We will look into mitigating this in the future.

I'm going to close this as I'm pretty sure the performance hits you see are these expected differences due to how the two multihop solutions are implemented.

In the app we prefer maximum privacy over performance when it comes to multihop. Since the typical user of that feature is more privacy focused compared to performance focused.

**Comment by mikamidd** [comment]
Appreciate the detailed explanation. 
Excessive fragmentation seems to be the cause of this, my Wireshark knowledge is very basic but looking at the traffic log, it gets flooded with "fragmented IP protocol) notifications when in-app multihop is used regardless of the MTU setting.
WG mulithop as well as app single-hop have no fragmentation issues.
Hopefully this is something that's going to be improved in the future, apologies for bumping a closed thread.
