### ISSUE TITLE
Add context menu for system tray icon & fix bug with system tray box

### ISSUE THREAD

**Issue by Masterys** [mullvad/mullvadvpn-app#471]
This has been annoying me for a while but currently the desktop (PC/Windows) version of the Mullvad client does not have a context menu on the system tray icon (right clicking on the icon does not show a menu). It would be very useful to add menu options like Connect/Disconnect, Settings window and Exit. 

Also, when you open Mullvad, the system tray box does not automatically close and obscures buttons like this:
![screen](https://user-images.githubusercontent.com/20892641/45957219-ce6e1580-c014-11e8-88d9-9a194b8113a4.png)

These are very simple things but causes quite the annoyance.

**Comment by faern** [comment]
The missing context menu is by design. The entire app view is basically the context menu. Which is the reason the app is locked in place and opens just next to the icon, and can't be moved around. Clicking the tray icon and then disconnect/connect is only two clicks. So it would be exactly the same if it was performed via a context menu instead as well.

Yes, we are aware of the issue with all hidden tray icons obscuring the view in the way your screenshot shows. We want to fix this by making sure the Mullvad VPN tray icon never is hidden under this menu. You can do this yourself manually by dragging the tray icon from that submenu out to sit right next to the clock.

**Comment by Masterys** [comment]
Alright then, closing this in that case.
