### ISSUE TITLE
[feature request] Allow specifying manual (user owned) first-hop in wireguard multihop operation mode (would allow some interesting "user operated" obfuscation bridges, potentially also your own)

### ISSUE THREAD

**Issue by LindaFerum** [mullvad/mullvadvpn-app#4756]
## Issue report

Operating system: Android 13, rooted
App version: 2023.2

### Issue description

Not an issue but a humble feature request.
Allow users of android app to use multihop with their own wireguard server as first hop.

Should require some modest changes (explicit key export from android app?) 

Usecase:
on rooted devices this will allow using things like [UDP2RAW](https://github.com/wangyu-/udp2raw) (on a user-operated server) as an obfuscation bridge 

something like
[mullvad app on android] <>[UDP2RAW-local]<>[UDP2RAW-remote]<>[user-operated first-hop wireguard server]<>[mullvad]
will become doable 

Of course, obvious drawback would be that UDP2RAW requires root
non-root users might be able to do samewise with things like Shadowsocks  (though UDP2RAW's implementation of fake TCP is very sophisticated and IMVHO "worth rooting for")

This approach will allow very decent wireguard obfuscation while relieving some burden from mullvad (since such bridges would be user-operated)  

Potentially might be also useful for implementing Mullvad's own bridge system on android app but just giving the ability to specify "your own first hop" would be a good stopgap solution for users who can set up their own shadowsocks/udpspeeder/udp2raw servers and need obfuscation on mobile right now.

**Comment by faern** [comment]
Thank you for the feature request. We historically have turned down all features requiring a rooted phone. And we will probably continue doing so for now. Even if the feature is cool, it helps such a small subset of the users. We think that it's more worthwhile spending that time implementing something that everyone can benefit from, even if it's slightly less effective than the rooted alternative.

Adding more obfuscation methods directly to WireGuard is definitely on the radar. So is potentially allowing WireGuard to go via (our) bridges. Adding support for third party bridges might also be desirable and end up in the planning. But we have not talked about making one of two WireGuard hops custom. It would be a bit hard to explain to users how to use it, given that you would need to extract your ephemeral* WireGuard key from the app and configure your own server to use it.

Currently you need to use the same WireGuard key for both the entry and exit locations, since they both use the same tunnel interface. We might want to split this into two interfaces on desktop, but we can't on Android.

*: The WireGuard key used my the Mullvad app is ephemeral. It's generated on the fly and periodically rotated in the background. The user should never need to see this key, nor should they persist it since it will soon change again. It would be a constant battle trying to keep the third party server up to date. That's not a battle the user should be engaged in. We are instead working towards having the WireGuard key even more ephemeral since that in turn has other privacy benefits.

Even though this issue contains some nice ideas, I'm going to close it since it's primarily about custom WireGuard *entry* relays, which is something that likely won't happen.
