### ISSUE TITLE
DoH custom DNS

### ISSUE THREAD

**Issue by eligibleshield** [mullvad/mullvadvpn-app#4759]
Why don't the Mullvad clients allow DoH custom DNS?

Why is IPv6 disabled by default on desktop?

**Comment by faern** [comment]
> Why don't the Mullvad clients allow DoH custom DNS?

Because there is no strong enough use case for DoH when you already have a VPN tunnel. And because we have not had the time or prioritized implementing it. Currently our app just takes your configured custom DNS and sets that in the OS. And not all OSes support DoH/supports it very differently. So it would probably be quite a large change, for questionable utility.

> Why is IPv6 disabled by default on desktop?

Because IPv6 is troublesome. The vast majority of people don't need it, so there is no strong argument for having it enabled by default. The people who want it can easily enable it. IPv6 is very often broken and/or has *terrible* peering/routing between providers and datacenters around the world. So having it enabled and making more people unknowingly use it will result in a lot worse connectivity *on average*. We have tried, and our ops/support team does not allow IPv6 by default due to the amount of issues and support cases it causes.

Many ISPs/hosting providers don't care at all about IPv6. It's not uncommon that we at Mullvad report broken IPv6 links to companies. Links that they themselves have failed to properly monitor.

I'm going to close this issue since it does not track a bug or feature request, but is just a (two) question(s). If you have further questions I recommend you contact support@mullvad.net.
