### ISSUE TITLE
mullvad update/install issue

### ISSUE THREAD

**Issue by saiakesani** [mullvad/mullvadvpn-app#4813]
Seeing as how i attempted to update the app, having recently paid for services, i thought id bring this up here, in order step by step

i launched Mullvad and it would not connect at all 

I attempted to update Mullvad seeing i was a version or two behind

It failed to update or install but when doing so i would get unable to close mullvad please close it manually and click retry

checked event viewer, and saw this, for each time i attempted to install the update
-----------------------
The description for Event ID 54 from source mullvad-split-tunnel cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

\Device\MULLVADSPLITTUNNEL

The message resource is present but the message was not found in the message table
-----------------------

**Comment by faern** [comment]
Can you please specify in detail what operating system/version you are using? And which version of Mullvad it is that you are trying to install exactly.

Looks like you are on Windows. Since the installer fails, can you please upload `C:\ProgramData\Mullvad VPN\install.log` here as well so we can see if it tells us anything useful?

**Comment by faern** [comment]
`ProgramData` is a hidden folder. Paste `C:\ProgramData\Mullvad VPN\` directly into the location bar at the top of your screenshot.

**Comment by saiakesani** [comment]
one moment please and thank you

**Comment by saiakesani** [comment]
[install.log](https://github.com/mullvad/mullvadvpn-app/files/11819347/install.log)

**Comment by faern** [comment]
Looks like you are trying to install version `2023.1` of our app. This is not the latest version. At the time of writing `2023.3` is the newest version. Please try installing that and see if it helps. I doubt it does since we have not touched anything around the split tunneling driver in a while, but always worth trying the latest software first.

The install log does not contain anything interesting. Can you please send a screenshot of the issue/error you are seeing while installing the latest version, please?

**Comment by saiakesani** [comment]
![image](https://github.com/mullvad/mullvadvpn-app/assets/81065354/d45d52b1-217c-419a-a7ea-9d944ee8bcfd)
same result as previous install

anything else i could send that might help?

**Comment by saiakesani** [comment]
https://github.com/mullvad/mullvadvpn-app/releases worked, went to assets, downloaded the top file, installed fine, how i tried getting it initially was through the website though if thats of any help

**Comment by faern** [comment]
Did you download the Windows installer for the same version, and it suddenly worked? Sounds like you had a corrupt download before then. Or did you go with `2023.4-beta1` this time and that made it work?

Either way, I'm closing this as it works for you now and this is not a problem we have heard from anyone else.
