### ISSUE TITLE
Remove update notification and icon mark when macOS version does not fit

### ISSUE THREAD

**Issue by gzqx** [mullvad/mullvadvpn-app#4860]
## Issue report

Operating system: MacOS 10.15
App version: 2023.3

### Issue description
The icon will have a dot aside it and a notification banner in the app every time it is opened. However, as the new version only works for Big Sur and higher, this notification is pointless to user with earlier version of macOS who do not intend to update it.

**Comment by gzqx** [comment]
Also given that Catalina still holds the majority of macOS market share, and people who haven't update will very unlikely to update in the future (since the radical change from Catalina to Big Sur), it would be really nice to support Catalina for some more time.

**Comment by faern** [comment]
> Also given that Catalina still holds the majority of macOS market share

What do you base this on? According to our own statistics, macOS 10.15 accounts for a pretty small portion of our macOS users. Maybe because of this?:

> Note that the source has indicated the fact that Apple has been reporting Big Sur 11 as Catalina 10.15, making its reported market share incorrectly high.  -- https://www.statista.com/statistics/944559/worldwide-macos-version-market-share/

I'm sorry, but maintaining software compatibility with a very large set of operating systems costs a lot of resources. If we supported very old versions of all OSes we would not have any time to implement features or fixing bugs on the newer OSes. As a result, the app would be way worse for the majority of our users.

People are in general pretty bad at updating software. Long term we want to have some kind of automatic update procedure to help with this. But until we have, allowing people to disable the update notification will probably do more harm than good.

May I ask what your aversion to macOS >=11 is? I'm just curious. If your hardware does not support upgrading that's one thing of course, but it sounded like you had other reasons.

**Comment by gzqx** [comment]
> Note that the source has indicated the fact that Apple has been reporting Big Sur 11 as Catalina 10.15, making its reported market share incorrectly high. -- [statista.com/statistics/944559/worldwide-macos-version-market-share](https://www.statista.com/statistics/944559/worldwide-macos-version-market-share/)

Ah, I see, that should be the reason of biased data I got, sorry for that.

> May I ask what your aversion to macOS >=11 is? I'm just curious. If your hardware does not support upgrading that's one thing of course, but it sounded like you had other reasons.

Since MacOS 10.13 (High Sierra), Apple started to make macOS less customizable, less open, less private and less free. In short: less like FreeBSD and more like iOS. MacOS 10.15 is the last MacOS that still remain some spirit of the tradition macOS (from Jobs era).

Notable examples include: Projects like mySIMBL and MacForge has to use reverse engineering to remain working, and finally all gave up to maintain several years ago;In new version Apple will check every executable by sending a hash of it to apple server, causing using mac without internet can speed it up significantly; the new UI design that "look modern" while showing much less information at the same time; etc.

Llike you pointed out  

>People are in general pretty bad at updating software. Long term we want to have some kind of automatic update procedure to help with this. But until we have, allowing people to disable the update notification will probably do more harm than good.

Cook can defend the change of macOS this way as well, but trusting security and privacy to any tech giant is not quite wise as well. ([Apple sued for collecting user data despite opt-outs](https://www.theregister.com/2022/11/14/apple_data_collection_lawsuit/))

BTW, will it break any ToS of mullvad if I build my own version of the client and remove the update banner?

**Comment by faern** [comment]
> BTW, will it break any ToS of mullvad if I build my own version of the client and remove the update banner?

Nope. The app is GPL licenced and open source. You are free to modify and compile it in whatever way you see fit for your needs :+1: 

> MacOS 10.15 is the last MacOS that still ...

Do you have a long term plan for what you will run? 10.15 will not be getting security updates. You seem to care about security and privacy, and not maintained software is pretty bad from a security standpoint. Unavoidably there will eventually be a security exploit in the software, and Apple won't fix it any longer.

We had the exact same thing happen with a bunch of users when we dropped Windows 7 support. They claim it's the last usable Windows version, and cling on to it. But they will stop getting security updates.

There are many ways to choose OS, but hanging on to one that is not getting updates is not a good strategy IMO. Mullvad will not support OSes that are not supported by their vendors, since we don't want to endorse usage of unmaintained software.

**Comment by gzqx** [comment]
> Do you have a long term plan for what you will run? 10.15 will not be getting security updates.

Thank you for reminding me of this! I have now moved back to Linux (Fedora) for all my new devices. It is just mbp's life length is usually very long and I expect to still use it for several years (not for main device and will hardly install any new software), thus I brought up this issue.

**Comment by faern** [comment]
Ok. Good you have a plan :)

I'm going to close this issue since we won't implement it (at least not as requested). Good luck fixing it yourself if it's too annoying to you to keep the update notification.
