### ISSUE TITLE
api.mullvad.net is blocked, please check your firewall

### ISSUE THREAD

**Issue by jkmpariab** [mullvad/mullvadvpn-app#503]
hey there
i have issue on ubuntu 18.04
when i enter account number, it doesn't connect and just throw an error saying: "api.mullvad.net is blocked, please check your firewall"
mullvad version: 2018.2 and 2018.3
system specs: ubuntu 18.04 64bit

**Comment by faern** [comment]
We are currently working on allowing logins to the app for users where the computer for some reason fail to communicate with our API. This is currently in beta. If you are willing to run beta software you can test it out by following our beta guides:
https://mullvad.net/en/guides/category/beta/

Otherwise this should be fixed in the stable 2018.4 release that will be out soon.

**Comment by jkmpariab** [comment]
> We are currently working on allowing logins to the app for users where the computer for some reason fail to communicate with our API. This is currently in beta. If you are willing to run beta software you can test it out by following our beta guides:
> https://mullvad.net/en/guides/category/beta/
> 
> Otherwise this should be fixed in the stable 2018.4 release that will be out soon.
