### ISSUE TITLE
login to account mullvad in android 12 

### ISSUE THREAD

**Issue by mohammadRezaeian** [mullvad/mullvadvpn-app#5048]
Operating system: Android 12
App version: 2023.5

Hi in my country mullvad is blocked
And I trying use others vpns login to mullvad account in software mullvad
But I don't know it's can't use openvpn/orbot for connect to api mullvad and login to account

**Comment by faern** [comment]
Our Android app uses Shadowsocks + our bridge servers to try reach our API and circumvent censorship. This might not work everywhere since the bridges might be blocked etc. Since censorship is a moving target and constantly changing, I suggest you contact support@mullvad.net for the latest tips and tricks on getting started!
