### ISSUE TITLE
Denmark server autopicking issue

### ISSUE THREAD

**Issue by HeXeeB** [mullvad/mullvadvpn-app#5120]
## Issue report

Operating system: Android 13 GrapheneOS(TQ3A.230805.001.2023090200) and Windows 10 pro 22h2

App version: 2023.4(Windows) and 2023.5(Android)

### Issue description
There are 4 servers in Denmark, all which you can independently pick by clicking on them. They all work when doing it that way. However if you choose to click on Denmark it should randomly pick from the 4 servers. It doesn't do this, it'll only pick the 401 or 402 server. The 001 and 002 server is never selected through this way. This happens on pc and mobile, but only for Denmark.Using wireguard only if that matters.

**Comment by HeXeeB** [comment]
I would do this through the app, but im guessing id get no response whether im just doing something wrong or if its a bug then. I did read the guidelines. Ill post the debug log here if you want it. Does the log contain any sensitive info? 

Alternatively let me know if I should rather contact the support email

**Comment by faern** [comment]
This actually works as expected even if it's a bit unclear to users. All servers have a boolean flag on them named `include_in_country`. If this is set to false, the server won't participate in random selection if the country it is in has been selected as the current location in the app. This is because some servers are less ideal to use for one reason or another, and then we have decided to mark them in this way, so only users specifically selecting their city, or that specific server, ends up connected to them.

The reasons for marking a server as not being included in country wide selection is up to the ops team, and I can't speak for them. But one reason might be that those servers might have worse peering. Which in the end has negative effects for users if they end up on them.

**Comment by HeXeeB** [comment]
I've been using the 001 server this whole time and never had any problems with it. It seems weird that the servers that are NOT included are the ones you guys own. Guess I'll wait for the filtering option feature for a semi fix to this "problem".

**Comment by HeXeeB** [comment]
There are 2 owned and 2 rented ones on Denmark. I'd rather use the owned ones. When filtering comes to mobile I should be able to filter owned/rented, then have it cycle through 001 and 002. Is that correct? @faern

**Comment by faern** [comment]
Yes. That is correct 👍
