### ISSUE TITLE
option use Shadowsocks bridge mullvad for login to account mullvad

### ISSUE THREAD

**Issue by mohammadRezaeian** [mullvad/mullvadvpn-app#5123]
Operating system: android

App version: 2023.6-beta1

### Issue description
Hi in my country api mullvad is block and I think it's good point if we can use bridge own mullvad for login to mullvad software
alternative use of others unsafe way

And really thanks for option use Shadowsocks for connections wireguard in Android 🙏🙏

**Comment by faern** [comment]
Hi. Our Android app is already using bridges to communicate with our API (to log in, among other things). It automatically tries new bridges until it works. If it's not working for you, you can try logging in a few more times to see if some other bridges work (every attempt tries ~3 bridges)

However, since censorship is an ever changing landscape, what worked yesterday might not work today. I recommend that you contact support@mullvad.net and ask for the best way currently to log in from your country.

> And really thanks for option use Shadowsocks for connections wireguard in Android 🙏🙏

This feature does not exist. At least not yet. But it's in our backlog.

I'm going to close this issue since I'm not sure what feature (that we don't already have) it's asking for.
