### ISSUE TITLE
Question: should I block DNS connections other than to MV servers?

### ISSUE THREAD

**Issue by ghost** [mullvad/mullvadvpn-app#5263]
## Issue report

Operating system: macOS, running Little Snitch

App version: 2023.5-beta2

### Issue description

I run the MV app with KS+lockdown mode, use DNS blockers and disable local network sharing. In the settings of my wifi connection, I list MV public servers (194.242... and 2a07::...).

However, upon startup, Little Snitch always tells me that mDNSresponder wants to connect to a series of IP addresses:
- 100.64.0....
- 224.0.0...
- fe80::f8ff::...
- ff02::fb (and nothing after that)
- doh.dns.apple.com

The first three, I believe, are local addresses, is that correct? Regardless of this, in order to avoid DNS leaks, what is the recommendation? Should these be allowed or blocked? And what is the implication if they are allowed?

Thanks!

**Comment by faern** [comment]
> 100.64.0....

Looks like our content blocking DNS. They all start with `100.64`. See here: https://github.com/mullvad/dns-blocklists. The `100/8` subnet is not technically local. It's used for carrier grade NAT, and we use it for some internal in-tunnel services (such as special content blocking DNS resolvers).

You should not see any requests like these outside the tunnel, if you do, they should be blocked.

> 224.0.0...
> fe80::f8ff::...
> ff02::fb (and nothing after that)
> doh.dns.apple.com

These are local/multicast etc. And the apple one is obviously apple's DNS over HTTPs. I guess you see these because they manage to leak before the system even starts our daemon. Sadly it's not possible for us to fully guarantee all no leaks on bootup since macOS does not allow us to specify when our service should start. You can see our docs about it here: https://github.com/mullvad/mullvadvpn-app/blob/main/docs/security.md#macos

This means probably not even little snitch is able to stop all leaks, unless they have figured out some way to circumvent this that I'm not aware of. Either way, if you don't want leaks, you should probably try to block these requests if you can. At least the non-local ones.

**Comment by xiaolilo** [comment]
Thanks a lot for this. I had thought that 100.64... was local; now I get it. I will try allowing just that one and blocking the other ones.
And, indeed, I get LS notifications very early in startup for this. 
My personal solution is to turn off wifi between turning off/rebooting and only turn on once everything is loaded.

**Comment by xiaolilo** [comment]
PS: when you say "You should not see any requests like these outside the tunnel, if you do, they should be blocked.", you mean the address below that sentence, right? The 100.64... ones are ok, yes?

**Comment by faern** [comment]
What do you mean by "OK"? That's up to you and your threat model. mDNS and DNS are two very different things and I'm just going to talk about DNS here: You probably don't want *any* DNS outside the tunnel if you are the type of user who disables wifi before rebooting to avoid leaks.

**Comment by xiaolilo** [comment]
PS: just tested now and if I block the mDNSresponder connection for 100.64.0.23 (so blocking all mDNS connections, since I already blocked the rest), websites are unreachable. When I unblock that one IP, it works.

**Comment by pinkisemils** [comment]
Are you verifying if these connections are leaking outside of the tunnel? You could verify this by trying to run `tcpdump` on the router to see what traffic is actually being sent out from your machine. When doing this, selecting a single relay to connect to can help, as then you can filter out all traffic to our relay IP and consider most other traffic to be a leak (barring DHCP). 

 It is perfectly normal for our app to send traffic to `100.64.0.23` if you have enabled DNS blocking and the app is connected. Little Snitch will detect any and all traffic trying leaving your computer, but as long as it's leaving your machine through our tunnel, we consider the app working as intended.
