### ISSUE TITLE
Disk space requirements

### ISSUE THREAD

**Issue by deanc** [mullvad/mullvadvpn-app#5275]
## Issue report

Operating system: MacOS 14.0 (2019 Intel MBP)

App version: Latest

### Issue description

![Screenshot 2023-10-12 at 9 34 10](https://github.com/mullvad/mullvadvpn-app/assets/232423/05b8e2e8-81ac-4912-8e1a-a6e2827c7f78)

As you can see here, the latest installer requires 512mb of disk space. I'm primarily curious if this could be addressed. Hugely functional apps like OBS, Pages, Numbers require less disk space than Mullvad. What is taking up so much room?

**Comment by raksooo** [comment]
This is discussed in the following issues as well:
https://github.com/mullvad/mullvadvpn-app/issues/1572
https://github.com/mullvad/mullvadvpn-app/issues/3085
https://github.com/electron/electron/issues/2003

Short summary:
We use Electron which bundles Chromium and that takes up a lot of space.

I'll close this since it's a duplicate.
