### ISSUE TITLE
[Feature Request] - Tools to combat DPI in countries such as Russia and Iran

### ISSUE THREAD

**Issue by dizelgerda** [mullvad/mullvadvpn-app#5341]
## Issue report

Operating system: IOS 17

App version: 2023.6

### Issue description

Mullvad is focused on the protection and confidentiality of user data. It would be great to see tools to bypass the locks — this is very important for countries like Russia and Iran that are trying to block VPN.

**Comment by faern** [comment]
This is a very generic feature request/issue. Yes, we are working on various anti-censorship techniques.

**Comment by dizelgerda** [comment]
Hello! Is there any progress, maybe an ETA?

**Comment by faern** [comment]
I'm going to close this as it's too generic to be actionable and considered "done". But yes, we have at least two anti-censorship features planned for the iOS app this quarter. We'll see if they are finished or not. But if they are, you should be able to reach our API via custom proxies, and reach our WireGuard servers via custom IPs.

**Comment by dizelgerda** [comment]
Very cool! Will you tell us about it in the blog after you leave? Or where can I find out about it?

**Comment by faern** [comment]
Probably in the app changelog itself. We might blog about it, that has not yet been decided.

**Comment by kukapishixdd** [comment]
any news?

**Comment by faern** [comment]
As I said, this issue is extremely generic, so I can only answer with very generic anti-censorship stuff:
* We have alternative API access methods in the app now. You can configure the app to use a custom proxy to reach our API for login and server lists etc. Available in the settings menu.
* We have WireGuard over TCP. A simple but sometimes very effective anti-censorship technique. Can get your tunnel working in places that block UDP, or that fingerprint WireGuard specifically, but fail to do so when it's inside a TCP stream.
