### ISSUE TITLE
Strange Multihop behavior on Linux Desktop App - Leak? 

### ISSUE THREAD

**Issue by arnoldschwarznnnn** [mullvad/mullvadvpn-app#5591]
Hello Guys! 
## Issue report
I have been using Mullvad App and multihop feature for some time. I have observed strange behavior on how the Multihop feature in the Desktop App and in standalone Wireguard with .conf used. 
**Test system**: Ubuntu 22.04.03
**Desktop App**: 2023.6
**Two NIC**: enps0s3 - main gateway, enp0s8 - shared to other computers
**Wireguard NICS:** wg-mullvad - created by the App, mullvad-with-multihop - created by "wg-quick up mullvad-with-multihop.conf"

### Issue description
**The observed strange issue using the App:** 
On the main network interface of the system, enp0s3, I see the Wireguard connection to the Entry server only. The App creates the  Wireguard interface "wg-mullvad". See screenshots below. So far all good. On the NIC wg-mullvad I expected to see only the wireguard traffic between me and the exit server. However, I see the wireguard traffic between me and exit server as well as my other non-mullvad, private, wireguard connection. 

As test, on different machine with same settings, with same NIC config, I used the standard CLI: wg-quick up mullvad-with-multihop.conf. On main gateway NIC enp0s3 I observed wireguard traffic of entry server **only**, on NIC mullvad-with-multihop I saw the typical normal user's encrypted traffic. **On NIC mullvad-with-multihop I did not see the wireguard traffic between me and the exit server of Mullvad, which tells the double tunnel functions correctly?** 

So how to explain this behavior of the App where within one tunnel I see Exit Servers traffic, where when wg-quick multihop.conf is used, I dont see the exit nodes traffic? Am I missing something here or is bug ? 

![image](https://github.com/mullvad/mullvadvpn-app/assets/153735690/0c0767f5-dccb-4f16-a2f8-4a2d501f193f)
![image](https://github.com/mullvad/mullvadvpn-app/assets/153735690/2e0dc979-b73e-4789-a943-4f293cd4f8ca)

![image](https://github.com/mullvad/mullvadvpn-app/assets/153735690/0b6dfb18-fb32-4acc-a23b-c4c68f133703)
![image](https://github.com/mullvad/mullvadvpn-app/assets/153735690/d54b8391-54a5-47cd-bb84-5fad36cad75f)

**Comment by faern** [comment]
WireGuard multihop in our app is implemented very differently from how it works in the static configs you can generate on our website for usage with vanilla WireGuard.

The behavior you see from our app is completely normal and expected. The way we implement multihop is that we have both the entry and exit peer configured on *one interface*, meaning all traffic passes through the same interface twice. So you see both the traffic from your regular programs, and the traffic to the exit relay pass through there.

You have `wg-mullvad` and it's the route that absorbs all your regular internet traffic. This traffic goes into WireGuard and is encrypted with the encryption key of the **exit server**. This means only the exit server can decrypt the traffic from your applications. This encrypted traffic is then sent to `wg-mullvad` again but destined for the exit server this time. It's picked up by WireGuard *again* and encrypted with the encryption key of the **entry server** and then sent out on your physical network interface.

That's why you see a mix of traffic on the same interface. If you want to verify this more carefully please look at how the routes are set up and how the peers on `wg-mullvad` are configured with `sudo wg show wg-mullvad` (please mind that the interface will change name to `wg0-mullvad` in the next release). You should also be able to see that the *number of packets* on `wg-mullvad` is double that of the number of packets leaving `enps0s3`, since all packets pass `wg-mullvad` twice before being emitted on the physical network.

I'm going to close this as it looks like it works as expected.
