### ISSUE TITLE
Mullvad VPN F-Droid version blocked at 2023.9

### ISSUE THREAD

**Issue by rollsicecream** [mullvad/mullvadvpn-app#5635]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

Since more than 2 weeks, the Mullvad VPN app on F-Droid is blocked at version 2023.9.

### Expected Behavior

It should be updated to the 2023.10 version (though there's the beta of it)

### Steps to Reproduce

1. Go to the F-Droid page of Mullvad VPN
2. Scroll down to releases/version
3. And then, as you can see, there's no stable 2023.10 release.

### Android version

All VPN-supported Android versions

### Device model

All

### Mullvad VPN app version

2023.9/2023.10

**Comment by albin-mullvad** [comment]
Hey! F-Droid releases are slower by nature since those releases are built on F-Droid infrastructure, which typically takes a few days. Also, we usually publish releases on GitHub and Google Play first since that way we can roll out slowly in order to detect and fix issues.

Here's the log of the `2023.10` build that hopefully will be published soon (probably today or tomorrow) by F-Droid:
https://monitor.f-droid.org/builds/log/net.mullvad.mullvadvpn/23100099#site-footer

**Comment by rollsicecream** [comment]
It got updated! Thanks.
