### ISSUE TITLE
Feature request]  Linux install: remove the buttons for direct .deb / .rpm file downloads

### ISSUE THREAD

**Issue by trytomakeyouprivate** [mullvad/mullvadvpn-app#5638]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

The repo is cool. And people should stop using the direct downloads, which is an "of course I do it like this" known from Windows and its bad.

The option would be to let the manually installed app add the repo on its own, and then update itself like that, but it does not work on Fedora Atomic Desktops, because the app is specifically the manually installed RPM and can't change to the repo one.

### Alternative solutions

users need to actively ignore the button, go to installation instructions and here the manual .deb and .rpm files are not even recommended. This is really weird.

### Type of feature

- [ ] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [X] Easier to use
- [X] Other

### Operating System

- [ ] Android
- [ ] iOS
- [ ] Windows
- [ ] macOS
- [X] Linux

**Comment by faern** [comment]
Thanks for the suggestion. We do aim to fix the download page to primarily recommend the repositories. Our web team just has not had the time yet, the repositories are pretty new.

I'm going to close this as it's a feature request on the website more than the app. Feedback like this is actually better directed at support@mullvad.net since they both write our guides and are in direct contact with all other teams at Mullvad to forward feedback about our service.
