### ISSUE TITLE
Unable to access `100.64.0.0/10` subnet (Tailscale)

### ISSUE THREAD

**Issue by RealOrangeOne** [mullvad/mullvadvpn-app#5921]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

When connected with Mullvad, an existing Tailscale connection stops working, and nodes become inaccessible. The "Local network sharing" subnets don't include `100.64.0.0/10`, which is used by Tailscale (and can't be changed)

### Expected Behavior

When connected to Mullvad, Tailscale nodes are still accessible.

I realise this can hinder other functionality, so perhaps it's best to have this opt-in somehow?

### Steps to Reproduce

1.Be connected to a Tailscale network
2. Enable Mullvad VPN
3. Notice Tailscale nodes are no longer accessible.

### Operating system version

Linux

### Mullvad VPN app version

2023.6

### Additional Information

I realise there's a partnership between Mullvad and Tailscale, which could eliviate my issue with this, but A) I'm not using `tailscale.com`'s controlplane, and B) I frequently use Mullvad to get around weird firewall configurations and captive portals, which Tailscale has a much harder time doing.

**Comment by MahdiNazemi** [comment]
If you are fine with compiling the app from source, you can refer to "Steps to reproduce" in the following bug report to add 100.64.0.0/10 in local networks:

https://github.com/tailscale/tailscale/issues/9479.

**Comment by RealOrangeOne** [comment]
That might work, but I'd rather not keep my own custom build of Mullvad around. If it's something of interest, I can open a PR, but I'd rather a reliable and sustainable solution be found.

**Comment by RealOrangeOne** [comment]
Unfortunately, neither manually adding a route for `tailscale0` nor modifying WireGuard with `wg set` seems to work around this, so it probably does need some modification in-app.

**Comment by MahdiNazemi** [comment]
Some people have been able to modify the routing table to allow VPN inter-op. Different solutions are shared in the following issue:

https://github.com/tailscale/tailscale/issues/2880

**Comment by raksooo** [comment]
@RealOrangeOne 100.64.0.0/10 isn't a local subnet and will therefore not be added to the list of allowed subnet. To allow traffic to that subnet you will need to add firewall rules for it. I saw in the linked issue (https://github.com/tailscale/tailscale/issues/2880) that there is an example of this, although I haven't verified that it works myself.

**Comment by rafa-br34** [comment]
For anyone reading this in the future, since no one mentioned:
Discussion on #9192 and #8976 (both of which are currently ongoing).
Duplicate of issues #8424 and #3218.

If you're willing to manually make a firewall route to skip WireGuard (which seems to be the only real option at the moment), @RealOrangeOne has written an excellent blog post which can be found [here](https://theorangeone.net/posts/tailscale-mullvad/). I have also written a post on SuperUser about how to skip ports from being routed via WireGuard (not related, but it can be helpful); I'll link it [here](https://superuser.com/a/1895195) for completeness.
I'm not sure of any real solutions for Windows other than emulating what's done on Linux, but if I find a method, I'll add to this.

I found a way to use Tailscale as a proxy. I'll insert it here for those who want a quick fix for Windows (and possibly Linux).
<details>
<summary>Running Tailscale as a proxy</summary>

Open two instances of CMD/PowerShell as administrator
Run `tailscaled --tun=userspace-networking --socks5-server=127.0.0.1:1055` in one instance  
Run `tailscale up --accept-dns=false --accept-routes=false` and wait for it to finish

Now you can simply use your desired program over the SOCKS5 proxy; in my case, it was SSH.  
Here's the SSH command I used `ssh user@100.x.x.x -o "ProxyCommand=ncat --proxy 127.0.0.1:1055 --proxy-type socks5 %h %p"`

If you get an error like `safesocket.Listen: namedpipe.Listen: open \\.\pipe\[...]\tailscaled: Access is denied.` Then that means that either `tailscaled` is already running, or you didn't run the command with enough privileges. To stop `tailscaled`, you can use `net stop Tailscale` as documented [here](https://tailscale.com/kb/1278/tailscaled#stopping-and-starting-tailscaled).

**Note**: This isn't by any means the most elegant workaround for this, and it fails sometimes. So if you can't seem to get it started, disable Mullvad, restart Tailscale entirely, including the service (`net stop Tailscale` and then `net start Tailscale`), and then join normally into the network before running the two commands and finally enabling Mullvad again.
</details>

**Comment by tritaum** [comment]
For anyone that needs an immediate solution for Linux I just created this mullvad daemon upstream-synced fork which allows you to exclude IPs/IP ranges from the mullvad tunnel, its very straightforward to setup, just replace your current daemon with the one in [Releases](https://github.com/tritaum/ip-split-tunneling-mullvad/releases) or install it directly using the AUR package named [patched-mullvad-vpn-daemon-bin](https://aur.archlinux.org/packages/patched-mullvad-vpn-daemon-bin)

If you want to check the source code, report bugs or make suggestions theres a Github repo for that:
https://github.com/tritaum/ip-split-tunneling-mullvad

If you're from another platform and need a solution for it you can create an issue in my repo
