### ISSUE TITLE
Allow cellular calls and text messages on Macs via iPhone

### ISSUE THREAD

**Issue by drasbeck** [mullvad/mullvadvpn-app#613]
As of version 2018.5 including (to the best of my knowledge) all prior releases, the functionality of making calls and sending text messages (not iMessage) from a Mac via an iPhone is not working, while the Mullvad client is enabled.

The two devices are connected to the same WiFi, and the preference for local network sharing is enabled in the client. 

When securely connected, trying to make a cellular call or send at text message from a Mac via an iPhone immediately fails. But successfully works as soon as the Mullvad client is disabled.

**Comment by faern** [comment]
Thanks for reporting this. This is very likely because of the same reason AirDrop and friends did not work a couple of versions ago. Apple probably uses some special protocol on some dedicated broadcast IP. We will have to test this and figure out how they do it so we can adjust the firewall rules accordingly. I'll make a not of this and we'll see when we get to it.

**Comment by drasbeck** [comment]
I can confirm that everything works perfectly. 🎉
