### ISSUE TITLE
Error on mullvad status

### ISSUE THREAD

**Issue by TimoKramer** [mullvad/mullvadvpn-app#633]
```
# mullvad status
Tunnel status: Connected
Error: Failed to call RPC method "get_current_location"
Caused by: JSON-RPC 2.0 Error: Internal error (Internal error)
```
```
# mullvad version                                                                      ~
Current version: 2018.5
Supported: true
Latest releases:
        latest stable: 2018.5
        latest: 2018.6-beta1
```
```
# uname -a
Linux kearch 4.19.4-arch1-1-ARCH #1 SMP PREEMPT Fri Nov 23 09:06:58 UTC 2018 x86_64 GNU/Linux
```
might be connected with #219

**Comment by faern** [comment]
I think this has been resolved. Please re-open if you are still experiencing this issue.

**Comment by jarbus** [comment]
I am having this exact issue on 2019.1

**Comment by macandchief** [comment]
Me too, on gnome. Also with latest beta.

**Comment by macandchief** [comment]
I'm sorry, it was on my side; actually I can confirm that "mullvad status" works fine, just tried it (using beta on debian with gnome).

Just for the record:
"Error: Failed to call RPC method "get_account_data"
Caused by: JSON-RPC 2.0 Error: Internal error (Internal error)"

Received this error message (and the client did not connect) because the system time was off.

**Comment by elimisteve** [comment]
I just faced this issue with Mullvad 2019.9 on Debian 9.11 (x86_64). Once I had a valid route to the internet I was able to generate a key no problem and this issue disappeared.
