### ISSUE TITLE
App takes too long to open

### ISSUE THREAD

**Issue by ali-zair** [mullvad/mullvadvpn-app#6454]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

The app's opening time is unacceptably long, as can be seen in the video below.

https://github.com/mullvad/mullvadvpn-app/assets/157414007/4555512e-098c-40bf-9b5a-6632dce3aef1

This issue occurs on a Samsung S23 Ultra, and I have also experienced this on a Samsung Fold 5. Both devices are running Android 14 and the latest version of Mullvad VPN (2024.3). However, I do **not** experience this issue on a Google Pixel 6 running GrapheneOS.

### Expected Behavior

The app should take around 2 seconds at maximum to open.

### Steps to Reproduce

1. Disconnect from Mullvad VPN (if already connected)
2. Close Mullvad VPN completely (by force-stopping it)
3. Open Mullvad VPN

### Android version

Android 14

### Device model

Samsung 23 Ultra

### Mullvad VPN app version

2024.3

**Comment by tintinTra** [comment]
I have the same Problem but on fedora kde 40,  I wasn´t sure if i should open another Thread so i'll just comment it here. 

### Current Behaviour 

The app needs like around *2~3* min to open. But *after* i *close* the app and open it up again. The window opens immediately. Connecting on the *Commandline* after boot and login is *no problem* and works right out of the box. It's only the gui-app. 

### Expected Behaviour

After booting and logging into your system. When you open the mullvad-gui app it should open up immediately.  

### Failure Logs

Jul 20 01:20:41 fedora mullvad-daemon[1455]: [mullvad_daemon::device][DEBUG] The current device is still valid
Jul 20 01:20:41 fedora mullvad-vpn[3616]: Warning: loader_add_layer_properties: 'layers' tag not supported until file version 1.0.1, but /usr/share/vulkan/implicit_layer.d/nvidia_layers.json is reporting version 1
Jul 20 01:20:41 fedora mullvad-vpn[3616]: DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
Jul 20 01:20:41 fedora mullvad-vpn[3616]: Error: ../src/nouveau/vulkan/nvk_physical_device.c:1109: VK_ERROR_INCOMPATIBLE_DRIVER
Jul 20 01:20:45 fedora mullvad-vpn[3616]: [3616:0720/012045.633568:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!

### Steps to Reproduce
Reboot & Launch mullvad app

### Mullvad VPN app version
2024.3

### Device Model 
Lenovo Thinkpad

### Additional Comment
I took the last few lines from journalctl. And the iussue is maybe my proprietary nvidia driver. Why it takes so long to start.

**Comment by Rawa** [comment]
Sorry for the late reply, I completely missed this issue. 

We've not been able to reproduce your issue on any of our test devices. Can you test if our latest [2024.4-beta02](https://github.com/mullvad/mullvadvpn-app/releases/tag/android%2F2024.4-beta2) resolves the issue? In 2024.4 we've reworked a ton of stuff behind the scenes that could affect this boot time.

**Comment by Rawa** [comment]
I'll close this issue for now, please re-open if the issue persists on the latest beta.
