### ISSUE TITLE
GUI does not show in Linux Mint 22 Beta (based on Ubuntu 24.04)

### ISSUE THREAD

**Issue by electricar** [mullvad/mullvadvpn-app#6468]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

1. Open the app
2. Doesn't show the GUI

### Expected Behavior

1. Open the app
2. Show the GUI

### Steps to Reproduce

1. Install .deb file from here (Intel x86_64, Ubuntu/Debian, Stable)
2. Open the installed app

### Operating system version

Linux Mint 22 Beta

### Mullvad VPN app version

2024.3

### Additional Information

I know Linux Mint is officially not supported, but I know that Mint is a popular distro and is used a lot, also in combination with Mullvad VPN.

The Mullvad VPN app is working fine in Linux Mint 21.3.

That's why I wondered if anybody here can help me out to get it working on Linux Mint 22 which is based on Ubuntu 24.04 (which is supported).

**Comment by MarkusPettersson98** [comment]
Hello, thanks for the bug report!

This is most likely caused by a missing apparmor profile: https://github.com/mullvad/mullvadvpn-app/issues/6128. It is automatically installed on Ubuntu 24.04 and future versions, but not on Ubuntu derivatives I'm afraid.

A workaround would be to run the [following commands manually](https://github.com/mullvad/mullvadvpn-app/pull/6196/files#diff-65d9525feb6a34a1592d31949bc778fdd864c959b7d43cca4405cc59757b907dR23-R24). I'll lift this with the team to see what we can do about it.

**Comment by gamer191** [comment]
Related: https://www.shellhacks.com/linux-mint-find-ubuntu-version-it-is-based-on/


Alternatively, if you want to support all Ubuntu forks (including stock Ubuntu), you could grep /etc/os-release for `UBUNTU_CODENAME=noble`, although that's obviously not future-proof. If you wanted it to be future-proof, without it running on older versions, you'd need an extremely convoluted regex (eg `UBUNTU_CODENAME=(?i)(?!lunar|mantic)` but with all the past codenames. I don't know if the `(?i)` is needed, since I haven't looked at older Ubuntu versions)
Or perhaps `UBUNTU_CODENAME=[n-w]`, which, based on the current patterns, will work until 2029, and won't catch older versions that are newer than 2015 (see https://en.wikipedia.org/wiki/Ubuntu_version_history#Table_of_versions)

**Comment by electricar** [comment]
With the newest Linux 2024.4 version and the official Linux Mint 22 Cinnamon release, the app works again as it should.
Thank you very much!

**Comment by MarkusPettersson98** [comment]
We will finally start installing the AppArmor on all Linux distros that makes sense: https://github.com/mullvad/mullvadvpn-app/pull/8880
