### ISSUE TITLE
Split tunneling in mullvadvpn-app 2024.4 is not available on macos Monterey 12.7.5

### ISSUE THREAD

**Issue by netfortius** [mullvad/mullvadvpn-app#6539]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

Split tunneling in mullvadvpn-app 2024.4 is not available on macos Monterey 12.7.5

### Expected Behavior

Availability of split tunneling, as advertised for this version (2024.4)

### Steps to Reproduce

Run the app -> no menu option for split tunneling, in any category of settings

### Operating system version

macos Monterey 12.7.5

### Mullvad VPN app version

2024.4

**Comment by Kairzhan** [comment]
Confirm the same problem in Big Sur 11.7.10

**Comment by MarkusPettersson98** [comment]
Hello,

I want to clarify that split tunneling is only available on macOS 13 and later versions as noted on our website: https://mullvad.net/en/why-mullvad-vpn.

![image](https://github.com/user-attachments/assets/50700fb5-e678-49c3-8adc-fa2eb1ce55f0)

This is not likely to change because we officially only support the last 3 major releases of macOS, which currently is 13, 14 & 15. Sorry for the inconvenience :yellow_heart:
