### ISSUE TITLE
[Feature request] Provide apk from the github releases page

### ISSUE THREAD

**Issue by grrrrr** [mullvad/mullvadvpn-app#6560]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

Currently on the [releases](https://github.com/mullvad/mullvadvpn-app/releases) page, binaries are provided for the desktop only.

A little similar to #5606 I would like to request making the apk available on the release page, which would allow for easy fetching of Mullvad VPN from a trusted and potentially uncensored source,  using [Obtanium](https://github.com/ImranR98/Obtainium)

### Alternative solutions

Download the apk from the official Mullvad site, but this can be blocked in certain cases due to censorship or other reasons.

### Type of feature

- [X] Better privacy/anonymity
- [X] Better at circumventing censorship
- [X] Easier to use
- [ ] Other

### Operating System

- [X] Android
- [ ] iOS
- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by albin-mullvad** [comment]
Hey! Thanks for reporting, but we're a bit confused since we've been publishing the Android app on GitHub releases for many years. Please check the releases page again and look for releases with the `android/` prefix. Here's the latest stable Android release on GitHub: https://github.com/mullvad/mullvadvpn-app/releases/tag/android%2F2024.3

Could your issue be that Obtanium doesn't like how we publish? :thinking:

**Comment by grrrrr** [comment]
> Could your issue be that Obtanium doesn't like how we publish

I think that or I no computer well :facepalm:     Obtanium does need a bit of extra tweaking indeed to be more specific for android.
