### ISSUE TITLE
[Bug] PlayStore Beta Old Version

### ISSUE THREAD

**Issue by zero77** [mullvad/mullvadvpn-app#6634]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

There is a beta program on the Playstore and when you join, the app version is still the same as the stable.
At the time of opening this the beta version on the Playstore is android/2024.3 and the beta version on github is android/2024.4-beta2

### Expected Behavior

If you joined the beta program you should have android/2024.4-beta2 installed at the moment

### Steps to Reproduce

1. Join beta program
2. install mullvad vpn

**Comment by albin-mullvad** [comment]
Hey! Thanks for your interest in the upcoming release! :star2:  The reason for you seeing an older version in Google Play is that we're rolling out the release slowly since it includes significant changes to the app. 30% of our beta testers currently have access to the latest beta. You can expect the rollout to increase during the upcoming two weeks and reach 100% next week unless any significant issues are identified.

**Comment by albin-mullvad** [comment]
You're welcome! :slightly_smiling_face: The beta is pushed out via the Google Play Open testing track. Advanced users can always find it our GitHub releases as well.
