### ISSUE TITLE
Local network sharing doesn't seem to be working

### ISSUE THREAD

**Issue by mattberther** [mullvad/mullvadvpn-app#682]
Running the app on Mac OS Mojave 10.14.2. I've selected "Local network sharing" in the preferences tab. However, when I connect to the VPN and do something like: `ssh 192.168.1.4` it does not appear to route.

Is there something else I need to be doing to allow for this functionality?

**Comment by faern** [comment]
Can you ping that IP?
Is your mac on the same subnet? The local network sharing does currently not allow you to communicate between, for example, a `192.168.1.0/24` to a `192.168.0.0/24` network.
It works for me on macOS 10.14.2 here.

Please continue resolving this with support@mullvad.net rather than on github. They will be faster at responding and will likely know more on the topic.
