### ISSUE TITLE
Lockdown mode not working in WSL2

### ISSUE THREAD

**Issue by ttjamesdev** [mullvad/mullvadvpn-app#6997]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

When lockdown mode is active and VPN is disconnected, WSL2 can still access internet. For example:
```
$ curl http://3.229.60.214/ip
{
  "origin": "ORIGINAL IP ADDRESS"
}
```

3.229.60.214 is IP address of httpbin.org

### Expected Behavior

When lockdown mode is active and VPN is disconnected, WSL2 should NOT be able to access internet:
```
$ curl http://3.229.60.214/ip
curl: (7) Failed to connect to 3.229.60.214 port 80 after 0 ms: Couldn't connect to server
```

### Steps to Reproduce

1. Enable lockdown mode
2. Disconnect VPN
3. In WSL2 run `curl http://3.229.60.214/ip`

### Operating system version

Windows 10 (22H2)

### Mullvad VPN app version

2024.5

### Additional Information

```
$ cat /etc/resolv.conf
nameserver 10.64.0.1
```

DNS is not working as expected when lockdown mode is active and VPN is disconnected. That's why it is needed to test with IP address instead of domain name.

**Comment by Serock3** [comment]
Hello. This is unfortunately an old known issue, which we blogged about a few years back <https://mullvad.net/en/blog/linux-under-wsl2-can-be-leaking>. The normal windows firewall is unable to block traffic coming form Hyper-V instances. We have recently elevated this issue internally since there is now limited support for Hyper-V-specific firewall rules. We are investigating solutions, but don't expect any updates in the near future. In the meantime, I would recommend installing the Linux version of the app inside of WSL 🙂
