### ISSUE TITLE
[Feature request] Support Wireguard with "mullvad bridge"

### ISSUE THREAD

**Issue by duxsco** [mullvad/mullvadvpn-app#7037]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

As App version [2024.6-beta1](https://github.com/mullvad/mullvadvpn-app/releases/tag/2024.6-beta1)  introduced Wireguard over Shadowsocks, I wish for `mullvad bridge` to support Wireguard in addition to already supported OpenVPN. That way, I can filter out rented bridge instances, choose specific locations and providers.

```
❯ mullvad version
Current version       : 2024.6-beta2
Is supported          : true
Suggested upgrade     : none
Latest stable version : 2024.5
Latest beta version   : 2024.6-beta2

❯ mullvad -h | grep bridge
  bridge           Manage use of bridges, socks proxies and Shadowsocks for OpenVPN. Can make OpenVPN tunnels use Shadowsocks via one of the Mullvad bridge servers. Can also make OpenVPN connect through any custom SOCKS5 proxy. These settings also affect how the app reaches the API over Shadowsocks

❯ mullvad bridge set -h
Set bridge state and settings, such as provider

Usage: mullvad bridge set <COMMAND>

Commands:
  state        Specify whether to use a bridge
  location     Set country or city to select relays from. Use the 'mullvad bridge list' command to show available alternatives
  custom-list  Set custom list to select relays from. Use the 'custom-lists list' command to show available alternatives
  provider     Set hosting provider(s) to select relays from. The 'list' command shows the available relays and their providers
  ownership    Filter relays based on ownership. The 'list' command shows the available relays and whether they're rented
  custom       Configure a SOCKS5 proxy
  help         Print this message or the help of the given subcommand(s)

Options:
  -h, --help     Print help
  -V, --version  Print version
```

### Alternative solutions

N/A

### Type of feature

- [X] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [ ] Easier to use
- [X] Other

### Operating System

- [ ] Android
- [ ] iOS
- [X] Windows
- [X] macOS
- [X] Linux

**Comment by MarkusPettersson98** [comment]
Hello! 

As it stands, `Wireguard over Shadowsocks` works by sending obfuscated traffic to the Wireguard relay that you are connected to. This works because the Shadowsocks proxy is hosted on the Wireguard relay itself.

As the help text in  `mullvad bridge` says: this command is used to manage the use of dedicated bridge servers for OpenVPN tunnels. These are entirely different servers from the aforementioned Wireguard relays.

To filter out rented relays, providers or choose specific locations, use the `mullvad relay set` command in this instance. We could probably do a better job explaining how `Wireguard over Shadowsocks` :blush:

**Comment by duxsco** [comment]
thx
