### ISSUE TITLE
Min and Target SDK

### ISSUE THREAD

**Issue by Jeffrey2307** [mullvad/mullvadvpn-app#7081]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

Hey,

i saw that the App has Target SDK on 34 and Minimum SDK on 26 and I wanted to ask if you could make Target SDK to 35 for Android 15 and Minimum SDK to 28/29/31? I would appreciate that! (Higher is always better)

A higher Minimum SDK version implies that your app supports fewer Android versions, minimizing compatibility issues. Because higher SDK means also Versions which are supported better. It makes the work easier. because Android 12 (SDK 31) is the last version that receives security patches. Further more, the less minSdk, the more internal compatibility layers, techniques etc. For example, lower SDK versions require v1/v2 signing, have somewhat different optimization levels, etc.

### Alternative solutions

At least Target SDK on 35 would be good because of Android 15.

### Type of feature

- [ ] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [ ] Easier to use
- [X] Other

### Operating System

- [X] Android
- [ ] iOS
- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by albin-mullvad** [comment]
Hey @Jeffrey2307! Thanks for the suggestion, we've been considering bumping the `minSdk` for a while, however there's both pros and cons to doing that so we consider that more of an internal decision. The `targetSdk` is already set to `35` [as seen here](https://github.com/mullvad/mullvadvpn-app/blob/4cb784d9cc05088b77781feb25b80c1953e16259/android/buildSrc/src/main/kotlin/Versions.kt#L6). It's also difficult to keep around issues for bumping various toolchain/dependency versions since they easily get outdated. Due to this I'm closing this issue.

As a more general comment, we would appreciate GitHub issues around what problems we can resolve or which features we can add. E.g. in this case if the new signing scheme (`v3`) has some benefit that you would like to make use of it would be better with an issues focused on that rather than which underlying SDK version we should support.
