### ISSUE TITLE
Shadowsocks does not connect - 

### ISSUE THREAD

**Issue by dentaku65** [mullvad/mullvadvpn-app#7092]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

When I try to use shadowsocks on Wireguard option the connection drops. Works only with Automatic.  

### Expected Behavior

Expecting connection with Shadowsocks

### Steps to Reproduce

1. In the gui interface select Settings, VPN Settings, Tunnel protocol [Wireguard], Wireguard settings, Shadowsocks

### Operating system version

Xubuntu 22.04.5 LTS

### Mullvad VPN app version

App 2024.6

### Additional Information

My telco provider give me an IP MAP-E with a specific range of ports; tried both automatic and one port allocated to me, but Shadowsocks does not connect. Tried Sweden and Swiss servers

**Comment by Serock3** [comment]
Hello, thanks for contacting us. Since you mention IP MAP-E this could possibly be an issue with how the app handles IPv6, but It's hard to tell without more information. Could you try these settings and see if they affect the issue?
* Does the same issue occur with the "UDP-over-TCP" obfuscation method? (Settings -> VPN Settings -> WireGuard Settings -> Obfuscation -> UDP-over-TCP)
* Have you tried enabling IPv6 inside the tunnel (Settings -> VPN Settings -> Enable IPv6),
* and outside the tunnel (Settings -> VPN Settings -> WireGuard Settings -> IP Version)?

If the issue remains, it would be useful if you could reproduce the problem and upload the logs here. You can find them by going to Settings -> Support -> Report a Problem -> View app logs.

**Comment by dentaku65** [comment]
Hello Serock3,

Thank you for answer

UDP-over-TCP -> is working
Enable IPv6 -> is working [this is enabled as my default setting]
IP Version -> IPv6 is set [this is my default]

Now the App version is 2024.7
[daemon.log](https://github.com/user-attachments/files/17580238/daemon.log)

**Comment by dentaku65** [comment]
Hello,

seems that dev version fix this issue
[daemon.log](https://github.com/user-attachments/files/17641740/daemon.log)

Thx

**Comment by Serock3** [comment]
Great! Thanks for finding the issue 🙌
