### ISSUE TITLE
2024.8 | Split tunneling, once activated, doesn't allow 'passed' apps to run

### ISSUE THREAD

**Issue by serrq** [mullvad/mullvadvpn-app#7151]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

I add two apps to split tunneling, for example Revolut and Netflix apps.

Then Mull and DuckDuckGo cannot reach internet.

### Expected Behavior

Mull and DuckDuckGo can reach internet.

### Steps to Reproduce

1. Set some apps to restriction (tunneling)
2. Open a browser and try to reach internet

### Android version

14

### Device model

OnePlus CPH2399

### Mullvad VPN app version

2024.8 fdroid

**Comment by MrChocolatine** [comment]
Same issue on my side. (device: Pixel 6a)

I feel like it is the same issue as #2877 where I also described a scenario where one of my app cannot reach internet when Split Tunneling is enabled:
https://github.com/mullvad/mullvadvpn-app/issues/2877#issuecomment-2408586576

**Comment by MrChocolatine** [comment]
@serrq , if you disable `Block connections without VPN` it should work (VPN > Settings > VPN Settings > Auto-connect & Lockdown mode).

But doing that is tedious...

**Comment by Pururun** [comment]
Hi @serrq 

I tested very quickly on my Pixel 7a running Android 15 and was not able to reproduce the issue.

Would it be possible to describe more in details what other settings you have? It seems that you `Block connections without VPN` turned on. This makes it so that the app that runs outside the tunnel are blocked. It should not affect apps that are inside the tunnel though.

Also if possible please provide logs which can be found under Settings -> Report a Problem - View Logs.

**Comment by Rawa** [comment]
> Disabling "connections without VPN" it runs properly but it makes no sense for me.

I understand how you feel, but this is an OS limitation which we are not able to change. With "Block connections without VPN", allowing apps outside the tunnel is not possible. This is described in the Split tunneling screen as well as on the last page of the Auto-connect & lockdown mode guide.
