### ISSUE TITLE
Killswitch on Android

### ISSUE THREAD

**Issue by PrivacyAndSecurity** [mullvad/mullvadvpn-app#7208]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

I would love this Feature on Androd too, because it helps against data being lost and our IP being exposed.

### Alternative solutions

Maybe a similar Function like that.

### Type of feature

- [X] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [X] Easier to use
- [ ] Other

### Operating System

- [X] Android
- [ ] iOS
- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by MrChocolatine** [comment]
The app has a built-in kill switch.

**Comment by MrChocolatine** [comment]
https://mullvad.net/en/help/using-mullvad-vpn-on-android#block-without-vpn

**Comment by MrChocolatine** [comment]
An extra kill switch ? What would the purpose of it? What would it do?

**Comment by albin-mullvad** [comment]
Hi @PrivacyAndSecurity! We understand your request, but what you're suggesting is not possible on Android due to OS limitations. We already block traffic when possible, which you can read more about [here](https://github.com/mullvad/mullvadvpn-app/blob/main/docs/security.md#android). Apart from that you should enable _Block connections without VPN_/_lockdown mode_ since that's the OS mechanism to prevent leaks (even though it has some limitations). Please let us know if you can share any resources (such as other apps or documentation) proving that there's something more we can do in our app. Closing for now.

@MrChocolatine thanks for the provided link to our website! :star2:
