### ISSUE TITLE
Internet blocked at at startup, need to start and quit client

### ISSUE THREAD

**Issue by sunflowr** [mullvad/mullvadvpn-app#744]
Hello, I'm using 2019.1 client on MacOS X High Sierra.
Suddenly yesterday my internet stopped working, and after lots of trial and error for over an hour I finally discovered that the only way to get internet back was to start the mullvad client and then quit it again. After that I could use internet again.
Anything I did until I done the above would be blocked even pinging.
I was happy thought I had finally solved it until I did a reboot and then I was blocked again.
Again, starting and quitting the mullvad client solved it. But I need to do this every time I start my computer.
I don't have the client auto start at boot time, nor do I have "block when disconnected" enabled.
I didn't do anything special when this suddenly started happening.
What can I do to fix this?

**Comment by sunflowr** [comment]
It seems my mullvad account was expired yesterday as well if that could give a clue to why this started happening yesterday. Please note that I didn't even have the mullvad client running at that time so it shouldn't have affected my connection in my opinion.

**Comment by sunflowr** [comment]
More or less confirmed it was the problem.
I paid for one more month and did a reboot and now my internet works instantly without having to start and quit the client.
So I guess there's some weird bug with the client?

**Comment by pronebird** [comment]
Hi @sunflowr,

We've addressed some of the issues with the blocked state due to insufficient funds on the account. The upcoming beta will offer a way to unblock the connection from the user interface, and automatically detect when a top-up happens.

**Comment by sunflowr** [comment]
Sounds good!  Thanks :)

**Comment by faern** [comment]
Did you have an older version of the app installed previously? Did you in that app ever activate the `Auto-connect` option? If so that would cause the system service to connect on boot, even when `Auto-start` was off. This behavior has been changed/simplified in 2019.1. But we do not overwrite existing settings.

Try opening the user interface and toggle both `Launch app on start-up` and `Auto-connect` back and fourth once. This should make sure the settings are in sync with the newer way they should interact with each other.

What you are describing really sounds like the system service is connecting when you are booting. And it does not sound like you want that behavior. Follow above instructions to disable it.

**Comment by faern** [comment]
Closing this issue since the auto-start/auto-connect settings are now more logical, and I provided instructions above. Please re-open if this is still a problem in some way.
