### ISSUE TITLE
Can't login to local docker registry.

### ISSUE THREAD

**Issue by ghost** [mullvad/mullvadvpn-app#772]
I'm using Mullvad 2019.2-beta1.

My hosts file has

`local-registry.com     127.0.0.1`

I need to push images to a local image registry. I am using this:

`$ docker login local-registry.com:5000`

It doesn't work when the vpn is connected. I can ping it:

```
$ ping local-registry.com
PING local-registry.com (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.080 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.067 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.090 ms
64 bytes from localhost (127.0.0.1): icmp_seq=4 ttl=64 time=0.105 ms
64 bytes from localhost (127.0.0.1): icmp_seq=5 ttl=64 time=0.070 ms
```

The error I am seeing is

```
$ docker login local-registry.com:5000
Authenticating with existing credentials...
Login did not succeed, error: Error response from daemon: Get http://local-registrymy-.com:5000/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

Login succeeds when the VPN is disconnected. I enabled local network sharing in the mullvad app as well.

**Comment by jmliz** [comment]
I am using Fedora Workstation 29 x64.

**Comment by faern** [comment]
Thanks for the report. The app should allow all traffic on the loopback interface to pass. So I'm thinking maybe `docker login` does something more than just use the loopback? Maybe docker sets up virtual network adapters whose IP range collide with those of the VPN tunnel? It is known that this firewall setup does not play very well with NATing between different LAN networks within the computer.

You could try dumping some traffic with `tcpdump` or Wireshark to see if you can spot anything not getting responses or otherwise sticks out?

**Comment by jmliz** [comment]
Will do. I am also seeing the problem in the stable version of the app.

**Comment by faern** [comment]
Is this still an issue? Otherwise I will close this.
