### ISSUE TITLE
[Features Requested] Server Load Indicator

### ISSUE THREAD

**Issue by scafroglia93** [mullvad/mullvadvpn-app#846]
It would be nice to include the average server load indicator within the application

**Comment by JimmyCushnie** [comment]
Yes, during peak hours it's quite annoying to have to try 5-10 different servers.

**Comment by faern** [comment]
We realize this might seem to be a problem and that might be fixed by server load indicators. But it's actually not. Our servers have a lot of spare capacity at all times. Neither CPU nor bandwidth is maxed out at virtually any point on any server.

The real problem is almost always throttling or problems with your ISP or the internet in general.

## ISPs regularly throttle UDP during "peak hours"

Suggested solution: Try connecting OpenVPN over TCP.

## ISPs regularly throttle traffic to destinations where they don't have direct peering

There is currently no simple way for users to see which provider our servers are hosted at. Neither is it easy/possible for users to know the peering relationships from your ISP all the way to said providers.

We have in the app backlog to show hosting provider for each server in the app. Then when you experience slow speeds it will at least be easier to pick a server at another provider.

## Conclusion

Showing server load will not help anyone and is nothing we plan on implementing. The reality is much more complex and nothing we can provide easy metrics for.
